# 04__preprocess_mpranalyze_compare
re-shape the counts data to run MPRAnalyze comparison mode.

In [3]:
import warnings
warnings.filterwarnings('ignore')

import itertools
import pandas as pd
import math
import matplotlib.pyplot as plt
import numpy as np
import re
import seaborn as sns
import sys

from scipy.stats import spearmanr

# import utils
sys.path.append("../../../utils")
from plotting_utils import *

%matplotlib inline
%config InlineBackend.figure_format = 'svg'
mpl.rcParams['figure.autolayout'] = False

In [4]:
sns.set(**PAPER_PRESET)
fontsize = PAPER_FONTSIZE

In [5]:
np.random.seed(2019)

## functions

In [6]:
def ctrl_status(row):
    if "SAMP_PAIR" in row.comp_id:
        return True
    else:
        return False

## Variables

In [7]:
mpranalyze_dir = "../../../data/01_counts/mpranalyze_files"

In [8]:
dna_counts_f = "%s/dna_counts.mpranalyze.for_quantification.CM.5.Mital.txt" % mpranalyze_dir
rna_counts_f = "%s/rna_counts.mpranalyze.for_quantification.CM.5.Mital.txt" % mpranalyze_dir

In [9]:
dna_counts_all_f = "%s/dna_counts.mpranalyze.for_quantification.CM.5.txt" % mpranalyze_dir
rna_counts_all_f = "%s/rna_counts.mpranalyze.for_quantification.CM.5.txt" % mpranalyze_dir

In [10]:
data_dir = "../../../data/02_activs"

In [11]:
dna_col_ann_f = "%s/dna_col_ann.mpranalyze.for_quantification.CM.5.Mital.txt" % mpranalyze_dir
rna_col_ann_f = "%s/rna_col_ann.mpranalyze.for_quantification.CM.5.Mital.txt" % mpranalyze_dir

In [12]:
human_vals_f = "%s/CM_vals.significance.5.txt" % data_dir

## 1. import data

In [13]:
dna_counts = pd.read_table(dna_counts_f, index_col=0)
#dna_counts = dna_counts.reset_index()
dna_counts.head()

,element,samp:dna_1__barc:1,samp:dna_1__barc:10,samp:dna_1__barc:11,samp:dna_1__barc:12,samp:dna_1__barc:13,samp:dna_1__barc:14,samp:dna_1__barc:15,samp:dna_1__barc:16,samp:dna_1__barc:17,...,samp:dna_1__barc:23,samp:dna_1__barc:24,samp:dna_1__barc:25,samp:dna_1__barc:3,samp:dna_1__barc:4,samp:dna_1__barc:5,samp:dna_1__barc:6,samp:dna_1__barc:7,samp:dna_1__barc:8,samp:dna_1__barc:9
0,AAACCCCCCGGGCCATTGTGTGTGTTTACGTAGGAAGGCGCTGCAT...,59.0,861.0,513.0,1356.0,34.0,593.0,675.0,1893.0,400.0,...,741.0,279.0,1614.0,2567.0,241.0,1041.0,1485.0,514.0,2323.0,846.0
1,AAACCCCCCGGGCCATTGTGTGTGTTTACGTAGGAAGGCGCTGCAT...,30.0,636.0,0.0,329.0,152.0,844.0,13.0,275.0,826.0,...,683.0,67.0,178.0,553.0,433.0,60.0,953.0,151.0,952.0,115.0
2,AAAGGGAATGTGTTCGAGACCTCTTTCGTCGGCCGATTGATTGAAT...,1430.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,271.0,222.0,30.0,0.0,0.0,0.0,0.0
3,AAATGTACGTATGCTGCTAGCCGGGCAGCCTCGAGATGGCCTCCCC...,3744.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1592.0,500.0,452.0,0.0,0.0,0.0,0.0
4,AACATTACACCAGGTGCGTTCGCAAACAGAACCATCCTCACGCGTG...,218.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4295.0,2459.0,3203.0,0.0,0.0,0.0,0.0

In [14]:
rna_counts = pd.read_table(rna_counts_f, index_col=0)
rna_counts=rna_counts.reset_index()
rna_counts.head()

,element,samp:CM_rep1__barc:1,samp:CM_rep1__barc:10,samp:CM_rep1__barc:11,samp:CM_rep1__barc:12,samp:CM_rep1__barc:13,samp:CM_rep1__barc:14,samp:CM_rep1__barc:15,samp:CM_rep1__barc:16,samp:CM_rep1__barc:17,...,samp:CM_rep5__barc:23,samp:CM_rep5__barc:24,samp:CM_rep5__barc:25,samp:CM_rep5__barc:3,samp:CM_rep5__barc:4,samp:CM_rep5__barc:5,samp:CM_rep5__barc:6,samp:CM_rep5__barc:7,samp:CM_rep5__barc:8,samp:CM_rep5__barc:9
0,AAACCCCCCGGGCCATTGTGTGTGTTTACGTAGGAAGGCGCTGCAT...,14.0,126.0,90.0,280.0,9.0,92.0,220.0,428.0,144.0,...,84.0,19.0,317.0,492.0,65.0,137.0,277.0,118.0,415.0,72.0
1,AAACCCCCCGGGCCATTGTGTGTGTTTACGTAGGAAGGCGCTGCAT...,0.0,206.0,0.0,88.0,48.0,246.0,1.0,53.0,304.0,...,85.0,3.0,22.0,60.0,121.0,11.0,112.0,9.0,145.0,11.0
2,AAAGGGAATGTGTTCGAGACCTCTTTCGTCGGCCGATTGATTGAAT...,258.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,46.0,46.0,4.0,0.0,0.0,0.0,0.0
3,AAATGTACGTATGCTGCTAGCCGGGCAGCCTCGAGATGGCCTCCCC...,736.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,149.0,82.0,35.0,0.0,0.0,0.0,0.0
4,AACATTACACCAGGTGCGTTCGCAAACAGAACCATCCTCACGCGTG...,59.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,477.0,511.0,463.0,0.0,0.0,0.0,0.0

In [15]:
rna_counts_all = pd.read_table(rna_counts_all_f, index_col=0)
rna_counts_all=rna_counts_all.reset_index()

dna_counts_all = pd.read_table(dna_counts_all_f, index_col=0)
#dna_counts = dna_counts.reset_index()
dna_counts_all.head()

,element,samp:dna_1__barc:1,samp:dna_1__barc:10,samp:dna_1__barc:100,samp:dna_1__barc:11,samp:dna_1__barc:12,samp:dna_1__barc:13,samp:dna_1__barc:14,samp:dna_1__barc:15,samp:dna_1__barc:16,...,samp:dna_1__barc:90,samp:dna_1__barc:91,samp:dna_1__barc:92,samp:dna_1__barc:93,samp:dna_1__barc:94,samp:dna_1__barc:95,samp:dna_1__barc:96,samp:dna_1__barc:97,samp:dna_1__barc:98,samp:dna_1__barc:99
0,AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGT...,255.0,606.0,548.0,2348.0,483.0,432.0,2004.0,605.0,548.0,...,309.0,550.0,514.0,184.0,2389.0,154.0,818.0,1216.0,1103.0,3153.0
1,AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGT...,821.0,2343.0,767.0,2284.0,265.0,1494.0,727.0,495.0,590.0,...,347.0,1769.0,1054.0,1224.0,559.0,629.0,1970.0,2309.0,1478.0,229.0
2,AACAGTGAAAATGATAATTCAAACTAATACTGTTTACAGGGAGTTA...,0.0,364.0,262.0,662.0,85.0,0.0,499.0,173.0,255.0,...,616.0,350.0,8.0,148.0,49.0,0.0,205.0,728.0,533.0,173.0
3,AACAGTGAAAATGATAATTCAAACTAATACTGTTTACAGGGAGTTA...,1598.0,321.0,1013.0,314.0,303.0,461.0,311.0,303.0,418.0,...,517.0,324.0,84.0,533.0,721.0,192.0,24.0,226.0,221.0,382.0
4,ACAGACAATAACTCAGTGCCTGGCAAACAGTGAGCACTATGCAAAC...,230.0,317.0,52.0,56.0,653.0,529.0,264.0,131.0,321.0,...,474.0,164.0,37.0,420.0,302.0,162.0,214.0,137.0,969.0,674.0

In [16]:
CM_vals = pd.read_table(human_vals_f)
CM_vals.head()

,CM,CM_pval,CM_padj,element,tile_type,parse_details,name,tile_number,chrom,strand,actual_start,actual_end,snp,dupe_info,is_snp,CM_log,tile_id,type,sig,full_name
0,0.205892,0.373847,0.884949,AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGT...,CONTROL_SNP_INDIV,chr3:171858455:171858590__rs6445040__3:1718585...,chr3:171858455:171858590__rs6445040__3:1718585...,1,chr3,+,171858455,171858590,rs6445040,4625,68.0,-0.686360,4625,CONTROL_SNP_INDIV,not sig,chr3:171858455:171858590__rs6445040__3:1718585...
1,0.407816,0.000002,0.000069,AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGT...,CONTROL_BUT_HAS_SNP,chr3:171858455:171858590__rs6445040__3:1718585...,chr3:171858455:171858590__rs6445040__3:1718585...,1,chr3,+,171858455,171858590,none,4625,0.0,-0.389536,4625,CONTROL_BUT_HAS_SNP,sig,chr3:171858455:171858590__rs6445040__3:1718585...
2,0.168798,0.676573,0.884949,AACAGTGAAAATGATAATTCAAACTAATACTGTTTACAGGGAGTTA...,CONTROL_SNP_INDIV,chr9:104195602:104195737__rsFakeAldoB101__9:10...,chr9:104195602:104195737__rsFakeAldoB101__9:10...,1,chr9,+,104195602,104195737,rsFakeAldoB101,4621,68.0,-0.772633,4621,CONTROL_SNP_INDIV,not sig,chr9:104195602:104195737__rsFakeAldoB101__9:10...
3,0.178422,0.600955,0.884949,AACAGTGAAAATGATAATTCAAACTAATACTGTTTACAGGGAGTTA...,CONTROL_BUT_HAS_SNP,chr9:104195602:104195737__rsFakeAldoB101__9:10...,chr9:104195602:104195737__rsFakeAldoB101__9:10...,1,chr9,+,104195602,104195737,none,4621,0.0,-0.748552,4621,CONTROL_BUT_HAS_SNP,not sig,chr9:104195602:104195737__rsFakeAldoB101__9:10...
4,0.194269,0.469184,0.884949,ACAGACAATAACTCAGTGCCTGGCAAACAGTGAGCACTATGCAAAC...,CONTROL_SNP_INDIV,chr7:151541672:151541807__rs60002611__7:151541...,chr7:151541672:151541807__rs60002611__7:151541...,1,chr7,+,151541672,151541807,rs60002611,4627,68.0,-0.711597,4627,CONTROL_SNP_INDIV,not sig,chr7:151541672:151541807__rs60002611__7:151541...

In [17]:
CM_vals.tile_type.value_counts()

WILDTYPE_BUT_HAS_SNP    4674
WILDTYPE_SNP_INDIV      4664
RANDOM                   335
CONTROL_SNP_INDIV         21
CONTROL_BUT_HAS_SNP       21
Name: tile_type, dtype: int64

## 2. Filter sequences with low counts

In [18]:
# filter out any elements we removed at initial steps (low dna counts)
CM_vals = CM_vals[CM_vals["element"].isin(dna_counts_all["element"])]

In [19]:
CM_vals.shape

(9715, 20)

## 3. Make files needed for seq comparison (WT/SNP)

In [20]:
dna_counts_CM = CM_vals[["element", "tile_type", "tile_id"]].merge(dna_counts, on="element").drop_duplicates()
dna_counts_CM.head()

,element,tile_type,tile_id,samp:dna_1__barc:1,samp:dna_1__barc:10,samp:dna_1__barc:11,samp:dna_1__barc:12,samp:dna_1__barc:13,samp:dna_1__barc:14,samp:dna_1__barc:15,...,samp:dna_1__barc:23,samp:dna_1__barc:24,samp:dna_1__barc:25,samp:dna_1__barc:3,samp:dna_1__barc:4,samp:dna_1__barc:5,samp:dna_1__barc:6,samp:dna_1__barc:7,samp:dna_1__barc:8,samp:dna_1__barc:9
0,AAACCCCCCGGGCCATTGTGTGTGTTTACGTAGGAAGGCGCTGCAT...,WILDTYPE_SNP_INDIV,4670,59.0,861.0,513.0,1356.0,34.0,593.0,675.0,...,741.0,279.0,1614.0,2567.0,241.0,1041.0,1485.0,514.0,2323.0,846.0
1,AAACCCCCCGGGCCATTGTGTGTGTTTACGTAGGAAGGCGCTGCAT...,WILDTYPE_BUT_HAS_SNP,4670,30.0,636.0,0.0,329.0,152.0,844.0,13.0,...,683.0,67.0,178.0,553.0,433.0,60.0,953.0,151.0,952.0,115.0
2,AAAGGGAATGTGTTCGAGACCTCTTTCGTCGGCCGATTGATTGAAT...,RANDOM,3,1430.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,271.0,222.0,30.0,0.0,0.0,0.0,0.0
3,AAATGTACGTATGCTGCTAGCCGGGCAGCCTCGAGATGGCCTCCCC...,RANDOM,2,3744.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1592.0,500.0,452.0,0.0,0.0,0.0,0.0
4,AACATTACACCAGGTGCGTTCGCAAACAGAACCATCCTCACGCGTG...,RANDOM,9,218.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4295.0,2459.0,3203.0,0.0,0.0,0.0,0.0

In [21]:
print(len(dna_counts_CM))

472

In [22]:
dna_counts_CM_all = CM_vals[["element", "tile_type", "tile_id"]].merge(dna_counts_all, on="element").drop_duplicates()
dna_counts_CM_all.head()

,element,tile_type,tile_id,samp:dna_1__barc:1,samp:dna_1__barc:10,samp:dna_1__barc:100,samp:dna_1__barc:11,samp:dna_1__barc:12,samp:dna_1__barc:13,samp:dna_1__barc:14,...,samp:dna_1__barc:90,samp:dna_1__barc:91,samp:dna_1__barc:92,samp:dna_1__barc:93,samp:dna_1__barc:94,samp:dna_1__barc:95,samp:dna_1__barc:96,samp:dna_1__barc:97,samp:dna_1__barc:98,samp:dna_1__barc:99
0,AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGT...,CONTROL_SNP_INDIV,4625,255.0,606.0,548.0,2348.0,483.0,432.0,2004.0,...,309.0,550.0,514.0,184.0,2389.0,154.0,818.0,1216.0,1103.0,3153.0
1,AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGT...,CONTROL_BUT_HAS_SNP,4625,821.0,2343.0,767.0,2284.0,265.0,1494.0,727.0,...,347.0,1769.0,1054.0,1224.0,559.0,629.0,1970.0,2309.0,1478.0,229.0
2,AACAGTGAAAATGATAATTCAAACTAATACTGTTTACAGGGAGTTA...,CONTROL_SNP_INDIV,4621,0.0,364.0,262.0,662.0,85.0,0.0,499.0,...,616.0,350.0,8.0,148.0,49.0,0.0,205.0,728.0,533.0,173.0
3,AACAGTGAAAATGATAATTCAAACTAATACTGTTTACAGGGAGTTA...,CONTROL_BUT_HAS_SNP,4621,1598.0,321.0,1013.0,314.0,303.0,461.0,311.0,...,517.0,324.0,84.0,533.0,721.0,192.0,24.0,226.0,221.0,382.0
4,ACAGACAATAACTCAGTGCCTGGCAAACAGTGAGCACTATGCAAAC...,CONTROL_SNP_INDIV,4627,230.0,317.0,52.0,56.0,653.0,529.0,264.0,...,474.0,164.0,37.0,420.0,302.0,162.0,214.0,137.0,969.0,674.0

In [23]:
rna_counts_CM = CM_vals[["element", "tile_type", "tile_id"]].merge(rna_counts, on="element").drop_duplicates()
rna_counts_CM.sample(5)

,element,tile_type,tile_id,samp:CM_rep1__barc:1,samp:CM_rep1__barc:10,samp:CM_rep1__barc:11,samp:CM_rep1__barc:12,samp:CM_rep1__barc:13,samp:CM_rep1__barc:14,samp:CM_rep1__barc:15,...,samp:CM_rep5__barc:23,samp:CM_rep5__barc:24,samp:CM_rep5__barc:25,samp:CM_rep5__barc:3,samp:CM_rep5__barc:4,samp:CM_rep5__barc:5,samp:CM_rep5__barc:6,samp:CM_rep5__barc:7,samp:CM_rep5__barc:8,samp:CM_rep5__barc:9
225,CTCGGGCGGGGCCTGGGACAGGCAGCTCCGGGGTCCGCGGTTTCAC...,WILDTYPE_SNP_INDIV,4687,366.0,7.0,142.0,101.0,36.0,0.0,153.0,...,14.0,8.0,155.0,0.0,242.0,17.0,0.0,45.0,0.0,19.0
382,TATCGCCTTCGGTAACCTGCCAAGAACGCATTCCAGCTAAATTGGG...,RANDOM,1,68.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,43.0,134.0,433.0,0.0,0.0,0.0,0.0
158,CCCTCCCCCGGCCTCCAGTCCCTCCCAGGGCCGCTTCGCAGAGCGG...,WILDTYPE_BUT_HAS_SNP,4698,0.0,0.0,0.0,0.0,42.0,0.0,0.0,...,0.0,0.0,0.0,33.0,0.0,0.0,10.0,0.0,0.0,0.0
347,GTCGCGGGCGGCGGGCGCAGGTGGGGAGGGGCGGCCGGAGCGCGTC...,WILDTYPE_SNP_INDIV,4653,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
362,GTTGGGTAATACAGGTCATTTCGCTTTGCGAGGCAGACCTAAGGAC...,RANDOM,1,40.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,66.0,65.0,12.0,0.0,0.0,0.0,0.0

In [24]:
print(len(rna_counts_CM))

472

In [25]:
rna_counts_CM_all = CM_vals[["element", "tile_type", "tile_id"]].merge(rna_counts_all, on="element").drop_duplicates()
rna_counts_CM_all.sample(5)

,element,tile_type,tile_id,samp:CM_rep1__barc:1,samp:CM_rep1__barc:10,samp:CM_rep1__barc:100,samp:CM_rep1__barc:11,samp:CM_rep1__barc:12,samp:CM_rep1__barc:13,samp:CM_rep1__barc:14,...,samp:CM_rep5__barc:90,samp:CM_rep5__barc:91,samp:CM_rep5__barc:92,samp:CM_rep5__barc:93,samp:CM_rep5__barc:94,samp:CM_rep5__barc:95,samp:CM_rep5__barc:96,samp:CM_rep5__barc:97,samp:CM_rep5__barc:98,samp:CM_rep5__barc:99
2668,ATTAACAATGGTTAGAAAATATAATGGAAAAAAATCTCTTACAAGA...,WILDTYPE_BUT_HAS_SNP,506,26.0,7.0,NaN,0.0,0.0,31.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
649,AAGCAGAATTACTGTAGTTCCTCAATCTTTAAAAATTATTATTTTG...,WILDTYPE_SNP_INDIV,535,0.0,49.0,NaN,0.0,3.0,20.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,AAAAATCAGCCGGGTGGGGTGGTGCATGTCTGTAGTCTCAGCTACG...,WILDTYPE_SNP_INDIV,584,101.0,85.0,NaN,72.0,68.0,56.0,174.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9252,TTGAGTGCTAACTACATCTTTAGGATTTCTCTCTCTCTCTCTTTCT...,WILDTYPE_SNP_INDIV,206,37.0,110.0,NaN,76.0,109.0,93.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6656,GTCATCAGGTTCATCTATGTTTTTCCCTCTTAAAGAAAGACAATCT...,WILDTYPE_BUT_HAS_SNP,826,35.0,0.0,NaN,0.0,0.0,0.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
rna_counts_CM.sample(5)

,element,tile_type,tile_id,samp:CM_rep1__barc:1,samp:CM_rep1__barc:10,samp:CM_rep1__barc:11,samp:CM_rep1__barc:12,samp:CM_rep1__barc:13,samp:CM_rep1__barc:14,samp:CM_rep1__barc:15,...,samp:CM_rep5__barc:23,samp:CM_rep5__barc:24,samp:CM_rep5__barc:25,samp:CM_rep5__barc:3,samp:CM_rep5__barc:4,samp:CM_rep5__barc:5,samp:CM_rep5__barc:6,samp:CM_rep5__barc:7,samp:CM_rep5__barc:8,samp:CM_rep5__barc:9
274,GCATATCATGACATTGTGCACACGTTCGCATCGCCCACATGGCGTC...,RANDOM,1,70.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,46.0,20.0,0.0,0.0,0.0,0.0
404,TCGGACCAACCCTGAGTTTCGCCCCCTATTGATAGCCTCCCGCTCA...,WILDTYPE_SNP_INDIV,4669,40.0,63.0,95.0,20.0,27.0,233.0,525.0,...,91.0,67.0,73.0,125.0,109.0,296.0,135.0,491.0,56.0,102.0
39,ACTGGGCATATCACCCTCGGTAGCGGATTAAGCATTTCTATGTCAC...,RANDOM,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,43.0,9.0,79.0,0.0,0.0,0.0,0.0
22,ACATGCCTCACCAGCGCCATATTTAGGATTTATTTCCCCGATACGA...,RANDOM,2,20.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,58.0,3.0,92.0,0.0,0.0,0.0,0.0
58,AGATGACGTCACCTCCAGGAGGACTCGCTTTTTCATTAATGAAACC...,WILDTYPE_SNP_INDIV,4699,157.0,0.0,2.0,2.0,0.0,0.0,0.0,...,10.0,98.0,0.0,41.0,0.0,18.0,0.0,146.0,25.0,45.0

In [27]:
rna_counts_CM_SNP = rna_counts_CM[rna_counts_CM.tile_type.str.contains('INDIV')]
rna_counts_CM_SNP.sample(5)

,element,tile_type,tile_id,samp:CM_rep1__barc:1,samp:CM_rep1__barc:10,samp:CM_rep1__barc:11,samp:CM_rep1__barc:12,samp:CM_rep1__barc:13,samp:CM_rep1__barc:14,samp:CM_rep1__barc:15,...,samp:CM_rep5__barc:23,samp:CM_rep5__barc:24,samp:CM_rep5__barc:25,samp:CM_rep5__barc:3,samp:CM_rep5__barc:4,samp:CM_rep5__barc:5,samp:CM_rep5__barc:6,samp:CM_rep5__barc:7,samp:CM_rep5__barc:8,samp:CM_rep5__barc:9
440,TGGTTTCTGGCAGTGAGTAGGGGGAGGGGATGGCAGGGGAAGCATA...,WILDTYPE_SNP_INDIV,4702,219.0,18.0,421.0,128.0,0.0,28.0,74.0,...,10.0,64.0,94.0,29.0,36.0,0.0,18.0,20.0,64.0,70.0
339,GGTTGGATTACACAATTGGACATTGCTCTCGGTGGTGACCTGCGCT...,WILDTYPE_SNP_INDIV,4696,50.0,148.0,54.0,117.0,69.0,34.0,34.0,...,29.0,39.0,44.0,5.0,80.0,6.0,16.0,60.0,8.0,12.0
265,GATCGCTTGGCGGTCTACATCGACCGTGTGCGCTCGCTGGAAACGG...,WILDTYPE_SNP_INDIV,4645,39.0,76.0,12.0,16.0,80.0,39.0,50.0,...,89.0,73.0,70.0,110.0,150.0,167.0,88.0,14.0,188.0,144.0
176,CCTGGGCTGCAGGGCAGGCTGGATGGAAGGACAGATGGGTAGTGGG...,WILDTYPE_SNP_INDIV,4668,43.0,126.0,37.0,1009.0,133.0,106.0,146.0,...,63.0,246.0,21.0,292.0,246.0,0.0,315.0,252.0,10.0,94.0
304,GGAGTTAGGAGCTCCGCCCCGAGGTCCCCGCCCATTCCCCGCTGGG...,WILDTYPE_SNP_INDIV,4684,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
rna_counts_CM_WT = rna_counts_CM[rna_counts_CM.tile_type.str.contains('HAS_SNP')]
rna_counts_CM_WT.sample(5)

,element,tile_type,tile_id,samp:CM_rep1__barc:1,samp:CM_rep1__barc:10,samp:CM_rep1__barc:11,samp:CM_rep1__barc:12,samp:CM_rep1__barc:13,samp:CM_rep1__barc:14,samp:CM_rep1__barc:15,...,samp:CM_rep5__barc:23,samp:CM_rep5__barc:24,samp:CM_rep5__barc:25,samp:CM_rep5__barc:3,samp:CM_rep5__barc:4,samp:CM_rep5__barc:5,samp:CM_rep5__barc:6,samp:CM_rep5__barc:7,samp:CM_rep5__barc:8,samp:CM_rep5__barc:9
348,GTCGCGGGCGGCGGGCGCAGGTGGGGAGGGGCGGCCGGAGCGCGTC...,WILDTYPE_BUT_HAS_SNP,4653,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0
275,GCCAGACATTCCTGCCTTCCTGCAGCCAAGTTTCCGATGTGCTGTT...,WILDTYPE_BUT_HAS_SNP,4673,110.0,95.0,16.0,43.0,1.0,123.0,148.0,...,156.0,66.0,123.0,32.0,81.0,21.0,110.0,46.0,87.0,0.0
286,GCCGGTGAATTCGCTTTTCCTTAGGAAACTATTCACTGTGCTCATT...,WILDTYPE_BUT_HAS_SNP,4666,52.0,210.0,74.0,12.0,4.0,27.0,167.0,...,140.0,92.0,0.0,45.0,19.0,15.0,13.0,131.0,268.0,3.0
9,AACGGAAAGGAAAAAGAAAAGAGAAAGAAAGAAAGAAAGAAAGAAA...,WILDTYPE_BUT_HAS_SNP,4707,0.0,23.0,8.0,0.0,29.0,52.0,29.0,...,38.0,0.0,0.0,13.0,0.0,5.0,0.0,0.0,0.0,0.0
216,CTCAGACAGCTTGGCAGGAACCTGAGGCCCTGTTTTTTTCCAGTCC...,WILDTYPE_BUT_HAS_SNP,4690,15.0,16.0,2.0,30.0,0.0,7.0,14.0,...,101.0,9.0,20.0,71.0,90.0,13.0,22.0,155.0,38.0,4.0

In [29]:
dna_counts_CM_WT = dna_counts_CM[dna_counts_CM.tile_type.str.contains('HAS_SNP')]
dna_counts_CM_SNP = dna_counts_CM[dna_counts_CM.tile_type.str.contains('INDIV')]
dna_counts_CM_WT.sample(5)

,element,tile_type,tile_id,samp:dna_1__barc:1,samp:dna_1__barc:10,samp:dna_1__barc:11,samp:dna_1__barc:12,samp:dna_1__barc:13,samp:dna_1__barc:14,samp:dna_1__barc:15,...,samp:dna_1__barc:23,samp:dna_1__barc:24,samp:dna_1__barc:25,samp:dna_1__barc:3,samp:dna_1__barc:4,samp:dna_1__barc:5,samp:dna_1__barc:6,samp:dna_1__barc:7,samp:dna_1__barc:8,samp:dna_1__barc:9
312,GGCCCCGGCGCCTCCTAAGACAGCCCGTGTCAGACGGCCAGAGCCC...,WILDTYPE_BUT_HAS_SNP,4667,475.0,588.0,1033.0,792.0,1446.0,223.0,364.0,...,1422.0,503.0,2952.0,1044.0,1115.0,1129.0,713.0,1809.0,759.0,515.0
348,GTCGCGGGCGGCGGGCGCAGGTGGGGAGGGGCGGCCGGAGCGCGTC...,WILDTYPE_BUT_HAS_SNP,4653,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,48.0,0.0,0.0,0.0,0.0,0.0,0.0
70,AGGCGCGGCGGCCGCACCCCACCCTGGGAAGAAACCGGCCAGGTGT...,WILDTYPE_BUT_HAS_SNP,4654,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,106.0,0.0
395,TCATGAAATCATGGCCATAGCTTTTTGAATGGTTAGTTTCAGTTGG...,WILDTYPE_BUT_HAS_SNP,4683,0.0,91.0,0.0,101.0,0.0,34.0,64.0,...,463.0,20.0,304.0,99.0,375.0,279.0,10.0,146.0,19.0,52.0
303,GGAGTTAGGAGCTCCGCCCCGAGGTCCCCGCCCATTCCCCGCTGGG...,WILDTYPE_BUT_HAS_SNP,4684,0.0,0.0,44.0,5.0,105.0,180.0,0.0,...,0.0,5.0,0.0,5.0,0.0,9.0,0.0,0.0,0.0,0.0

In [30]:
rna_map_seqs = rna_counts_CM_SNP.merge(rna_counts_CM_WT, left_on="tile_id", 
                                              right_on="tile_id", suffixes=("___seq:SNP","___seq:WT"))
rna_map_seqs.drop_duplicates(inplace=True)
print(len(rna_map_seqs))
rna_map_seqs.head(5)

68

,element___seq:SNP,tile_type___seq:SNP,tile_id,samp:CM_rep1__barc:1___seq:SNP,samp:CM_rep1__barc:10___seq:SNP,samp:CM_rep1__barc:11___seq:SNP,samp:CM_rep1__barc:12___seq:SNP,samp:CM_rep1__barc:13___seq:SNP,samp:CM_rep1__barc:14___seq:SNP,samp:CM_rep1__barc:15___seq:SNP,...,samp:CM_rep5__barc:23___seq:WT,samp:CM_rep5__barc:24___seq:WT,samp:CM_rep5__barc:25___seq:WT,samp:CM_rep5__barc:3___seq:WT,samp:CM_rep5__barc:4___seq:WT,samp:CM_rep5__barc:5___seq:WT,samp:CM_rep5__barc:6___seq:WT,samp:CM_rep5__barc:7___seq:WT,samp:CM_rep5__barc:8___seq:WT,samp:CM_rep5__barc:9___seq:WT
0,AAACCCCCCGGGCCATTGTGTGTGTTTACGTAGGAAGGCGCTGCAT...,WILDTYPE_SNP_INDIV,4670,14.0,126.0,90.0,280.0,9.0,92.0,220.0,...,85.0,3.0,22.0,60.0,121.0,11.0,112.0,9.0,145.0,11.0
1,AACGGAAAGGAAAAAGAAAAGAGAAAGAAAGAAAGAAAGAAAGAAA...,WILDTYPE_SNP_INDIV,4707,0.0,0.0,8.0,0.0,25.0,0.0,0.0,...,38.0,0.0,0.0,13.0,0.0,5.0,0.0,0.0,0.0,0.0
2,ACAAGACCCAGGCCCCGAGGAATCGCCTCCCTCCCGGCCCGACGTG...,WILDTYPE_SNP_INDIV,4695,2.0,15.0,31.0,3.0,0.0,8.0,0.0,...,0.0,17.0,1.0,4.0,0.0,18.0,0.0,9.0,5.0,1.0
3,ACCTGCGACGCCACCGGCTCTCCGATTCTGCGCGAGCCCTACTGGC...,WILDTYPE_SNP_INDIV,4651,135.0,883.0,324.0,470.0,614.0,313.0,659.0,...,108.0,596.0,32.0,68.0,0.0,193.0,40.0,870.0,197.0,806.0
4,ACCTGGCTTCAACCAGACGCTCGTAAATCTGTTTCTCTTGTTCCAC...,WILDTYPE_SNP_INDIV,4655,7.0,17.0,73.0,71.0,0.0,20.0,0.0,...,122.0,41.0,0.0,14.0,31.0,44.0,18.0,1.0,26.0,51.0

In [31]:
dna_map_seqs = dna_counts_CM_SNP.merge(dna_counts_CM_WT, left_on="tile_id", 
                                              right_on="tile_id", suffixes=("___seq:SNP","___seq:WT"))
dna_map_seqs.drop_duplicates(inplace=True)
print(len(dna_map_seqs))
dna_map_seqs.head(5)

68

,element___seq:SNP,tile_type___seq:SNP,tile_id,samp:dna_1__barc:1___seq:SNP,samp:dna_1__barc:10___seq:SNP,samp:dna_1__barc:11___seq:SNP,samp:dna_1__barc:12___seq:SNP,samp:dna_1__barc:13___seq:SNP,samp:dna_1__barc:14___seq:SNP,samp:dna_1__barc:15___seq:SNP,...,samp:dna_1__barc:23___seq:WT,samp:dna_1__barc:24___seq:WT,samp:dna_1__barc:25___seq:WT,samp:dna_1__barc:3___seq:WT,samp:dna_1__barc:4___seq:WT,samp:dna_1__barc:5___seq:WT,samp:dna_1__barc:6___seq:WT,samp:dna_1__barc:7___seq:WT,samp:dna_1__barc:8___seq:WT,samp:dna_1__barc:9___seq:WT
0,AAACCCCCCGGGCCATTGTGTGTGTTTACGTAGGAAGGCGCTGCAT...,WILDTYPE_SNP_INDIV,4670,59.0,861.0,513.0,1356.0,34.0,593.0,675.0,...,683.0,67.0,178.0,553.0,433.0,60.0,953.0,151.0,952.0,115.0
1,AACGGAAAGGAAAAAGAAAAGAGAAAGAAAGAAAGAAAGAAAGAAA...,WILDTYPE_SNP_INDIV,4707,20.0,0.0,103.0,0.0,168.0,0.0,0.0,...,113.0,0.0,0.0,23.0,0.0,54.0,9.0,74.0,0.0,0.0
2,ACAAGACCCAGGCCCCGAGGAATCGCCTCCCTCCCGGCCCGACGTG...,WILDTYPE_SNP_INDIV,4695,20.0,58.0,162.0,29.0,0.0,47.0,36.0,...,0.0,116.0,10.0,32.0,0.0,45.0,0.0,175.0,46.0,8.0
3,ACCTGCGACGCCACCGGCTCTCCGATTCTGCGCGAGCCCTACTGGC...,WILDTYPE_SNP_INDIV,4651,102.0,985.0,176.0,286.0,314.0,158.0,538.0,...,22.0,404.0,201.0,112.0,0.0,207.0,46.0,536.0,144.0,497.0
4,ACCTGGCTTCAACCAGACGCTCGTAAATCTGTTTCTCTTGTTCCAC...,WILDTYPE_SNP_INDIV,4655,16.0,150.0,422.0,476.0,21.0,127.0,10.0,...,1049.0,144.0,0.0,44.0,285.0,62.0,70.0,184.0,340.0,233.0

## 5. assign each pair an ID

In [32]:
dna_map_seqs["comp_id"] = dna_map_seqs["tile_id"].apply(str) + "__" + dna_map_seqs["tile_type___seq:SNP"]
rna_map_seqs["comp_id"] = rna_map_seqs["tile_id"].apply(str) + "__" + rna_map_seqs["tile_type___seq:SNP"]

In [33]:
# drop redundant cols
dna_map_seqs.drop(["element___seq:SNP", "tile_type___seq:SNP", "tile_id"], axis=1, inplace=True)
rna_map_seqs.drop(["element___seq:SNP", "tile_type___seq:SNP", "tile_id"], axis=1, inplace=True)
rna_map_seqs.sample(5)

,samp:CM_rep1__barc:1___seq:SNP,samp:CM_rep1__barc:10___seq:SNP,samp:CM_rep1__barc:11___seq:SNP,samp:CM_rep1__barc:12___seq:SNP,samp:CM_rep1__barc:13___seq:SNP,samp:CM_rep1__barc:14___seq:SNP,samp:CM_rep1__barc:15___seq:SNP,samp:CM_rep1__barc:16___seq:SNP,samp:CM_rep1__barc:17___seq:SNP,samp:CM_rep1__barc:18___seq:SNP,...,samp:CM_rep5__barc:24___seq:WT,samp:CM_rep5__barc:25___seq:WT,samp:CM_rep5__barc:3___seq:WT,samp:CM_rep5__barc:4___seq:WT,samp:CM_rep5__barc:5___seq:WT,samp:CM_rep5__barc:6___seq:WT,samp:CM_rep5__barc:7___seq:WT,samp:CM_rep5__barc:8___seq:WT,samp:CM_rep5__barc:9___seq:WT,comp_id
49,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4694__WILDTYPE_SNP_INDIV
13,62.0,36.0,181.0,16.0,0.0,17.0,36.0,8.0,57.0,110.0,...,90.0,59.0,6.0,44.0,53.0,219.0,46.0,53.0,15.0,4641__WILDTYPE_SNP_INDIV
41,90.0,82.0,33.0,78.0,202.0,30.0,32.0,106.0,109.0,0.0,...,66.0,123.0,32.0,81.0,21.0,110.0,46.0,87.0,0.0,4673__WILDTYPE_SNP_INDIV
26,252.0,14.0,104.0,22.0,16.0,71.0,171.0,21.0,41.0,38.0,...,87.0,115.0,103.0,32.0,56.0,7.0,66.0,0.0,53.0,4697__WILDTYPE_SNP_INDIV
9,25.0,21.0,3.0,129.0,45.0,12.0,27.0,16.0,162.0,2.0,...,0.0,19.0,0.0,0.0,14.0,111.0,0.0,31.0,14.0,4691__WILDTYPE_SNP_INDIV

In [34]:
# remove duplicates
dna_map_seqs.drop_duplicates(inplace=True)
print(len(dna_map_seqs))
print(len(dna_map_seqs["comp_id"].unique()))

rna_map_seqs.drop_duplicates(inplace=True)
print(len(rna_map_seqs))
print(len(rna_map_seqs["comp_id"].unique()))

68
68
68
68

In [36]:
rna_map_seqs = rna_map_seqs[rna_map_seqs['comp_id'].isin(dna_map_seqs['comp_id'].unique())]
print(len(rna_map_seqs))

68

## 6.1. pair positive controls together to serve as negative controls
I'm going to downsample each positive tile to 25 and 25 barcodes to serve as negative controls, as they come from the same sequence, no changes are expected

In [37]:
ctrl_ids = rna_counts_CM_all[rna_counts_CM_all['tile_type'].str.contains('CONTROL')].element.unique()
ctrl_ids[0:5]

array(['AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACATCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT',
       'AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACGTCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT',
       'AACAGTGAAAATGATAATTCAAACTAATACTGTTTACAGGGAGTTAAACTTCTACAGTGGGATTAAACGTCTGTACCACGTTAGCACAAATGTCACCTCTCTGTTAATCATAAAACAGGGTCACAGGCCAATGTT',
       'AACAGTGAAAATGATAATTCAAACTAATACTGTTTACAGGGAGTTAAACTTCTACAGTGGGATTAAAGGTCTGTACCACGTTAGCACAAATGTCACCTCTCTGTTAATCATAAAACAGGGTCACAGGCCAATGTT',
       'ACAGACAATAACTCAGTGCCTGGCAAACAGTGAGCACTATGCAAACACGAGTTATTATTTCTATCGTAAGTCATGGTCCAAAAGTTTGAAATACACTAACTTTCTGTGGCTCACTGTCTCTATTTCGTCACCAGC'],
      dtype=object)

In [38]:
dna_counts_CM.head()

,element,tile_type,tile_id,samp:dna_1__barc:1,samp:dna_1__barc:10,samp:dna_1__barc:11,samp:dna_1__barc:12,samp:dna_1__barc:13,samp:dna_1__barc:14,samp:dna_1__barc:15,...,samp:dna_1__barc:23,samp:dna_1__barc:24,samp:dna_1__barc:25,samp:dna_1__barc:3,samp:dna_1__barc:4,samp:dna_1__barc:5,samp:dna_1__barc:6,samp:dna_1__barc:7,samp:dna_1__barc:8,samp:dna_1__barc:9
0,AAACCCCCCGGGCCATTGTGTGTGTTTACGTAGGAAGGCGCTGCAT...,WILDTYPE_SNP_INDIV,4670,59.0,861.0,513.0,1356.0,34.0,593.0,675.0,...,741.0,279.0,1614.0,2567.0,241.0,1041.0,1485.0,514.0,2323.0,846.0
1,AAACCCCCCGGGCCATTGTGTGTGTTTACGTAGGAAGGCGCTGCAT...,WILDTYPE_BUT_HAS_SNP,4670,30.0,636.0,0.0,329.0,152.0,844.0,13.0,...,683.0,67.0,178.0,553.0,433.0,60.0,953.0,151.0,952.0,115.0
2,AAAGGGAATGTGTTCGAGACCTCTTTCGTCGGCCGATTGATTGAAT...,RANDOM,3,1430.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,271.0,222.0,30.0,0.0,0.0,0.0,0.0
3,AAATGTACGTATGCTGCTAGCCGGGCAGCCTCGAGATGGCCTCCCC...,RANDOM,2,3744.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1592.0,500.0,452.0,0.0,0.0,0.0,0.0
4,AACATTACACCAGGTGCGTTCGCAAACAGAACCATCCTCACGCGTG...,RANDOM,9,218.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,4295.0,2459.0,3203.0,0.0,0.0,0.0,0.0

In [39]:
for i, seq in enumerate(ctrl_ids):
    ctrl_ids[i] = ctrl_ids[i] + '__seq' + str(i)
ctrl_ids[0:5]

array(['AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACATCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT__seq0',
       'AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACGTCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT__seq1',
       'AACAGTGAAAATGATAATTCAAACTAATACTGTTTACAGGGAGTTAAACTTCTACAGTGGGATTAAACGTCTGTACCACGTTAGCACAAATGTCACCTCTCTGTTAATCATAAAACAGGGTCACAGGCCAATGTT__seq2',
       'AACAGTGAAAATGATAATTCAAACTAATACTGTTTACAGGGAGTTAAACTTCTACAGTGGGATTAAAGGTCTGTACCACGTTAGCACAAATGTCACCTCTCTGTTAATCATAAAACAGGGTCACAGGCCAATGTT__seq3',
       'ACAGACAATAACTCAGTGCCTGGCAAACAGTGAGCACTATGCAAACACGAGTTATTATTTCTATCGTAAGTCATGGTCCAAAAGTTTGAAATACACTAACTTTCTGTGGCTCACTGTCTCTATTTCGTCACCAGC__seq4'],
      dtype=object)

In [40]:
len(ctrl_ids)

42

In [41]:
ctrl_seqs = list([x.split("__")[0] for x in ctrl_ids])
samp_ids = set([x.split("__")[1] for x in ctrl_ids])

In [42]:
all_samp_id_pairs = list(itertools.chain.from_iterable(itertools.repeat(x, 3) for x in ctrl_seqs))
all_samp_id_pairs_str = ["%s__%s" % (x, x) for x in all_samp_id_pairs]
all_samp_id_pairs_str[0:5]

['AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACATCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT__AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACATCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT',
 'AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACATCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT__AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACATCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT',
 'AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACATCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT__AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACATCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT',
 'AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACGTCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT__AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACGTCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT',
 'AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACGTCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT__AAAGGCTGTGATTGTACGTGCAACTGTCATCTTGCTGGGATTGTGTAATGTCATGAGGCTGGGTTACGTCAATACCAAACTATGTTGCTTTCCTAGGAGGTTTTAAGTCCCTCTCAAGGGAGGTACTCAGGGTAT']

In [95]:
neg_ctrls_dna = pd.DataFrame()
neg_ctrls_rna = pd.DataFrame()
comp_id_list = []


for i, seq in enumerate(ctrl_seqs):
    print("ctrl #: %s" % (i+1))
    
    for j, samp_id_pair in enumerate(all_samp_id_pairs_str[0:3]):
        if j % 50 == 0:
            print("...samp pair #: %s" % (j+1))
        
        #samp1 = samp_id_pair.split("__")[0] # arbitrarily call 'snp' seq
        #samp2 = samp_id_pair.split("__")[1] # arbitrarily call 'wt' seq
        
        snp_sub_dna = dna_counts_CM_all[dna_counts_CM_all["element"] == seq]
        wt_sub_dna = dna_counts_CM_all[dna_counts_CM_all["element"] == seq]

        snp_sub_rna = rna_counts_CM_all[rna_counts_CM_all["element"] == seq]
        wt_sub_rna = rna_counts_CM_all[rna_counts_CM_all["element"] == seq]

        # re-name columns w/ species name
        snp_dna_cols = ["element"]
        wt_dna_cols = ["element"]
        snp_rna_cols = ["element"]
        wt_rna_cols = ["element"]

        columns_snp =  snp_sub_dna.drop(["element","tile_type",'tile_id'], axis=1, inplace=False)
        columns_wt =  wt_sub_dna.drop(["element","tile_type",'tile_id'], axis=1, inplace=False)

        random_snp = np.random.choice(columns_snp.columns,size=25, replace=False)
        random_wt = np.random.choice(columns_wt.columns,size=25, replace=False) 

        barcodes_snp = list([x.split("__")[1] for x in random_snp])
        barcodes_wt = list([x.split("__")[1] for x in random_wt])

        columns_snp_rna =  snp_sub_rna.drop(["element","tile_type",'tile_id'], axis=1, inplace=False)
        columns_wt_rna =  wt_sub_rna.drop(["element","tile_type",'tile_id'], axis=1, inplace=False)

        ## get rna columns to match barcodes
        snp_rna_cols_df = pd.DataFrame(columns_snp_rna.columns)
        wt_rna_cols_df = pd.DataFrame(columns_wt_rna.columns)

        snp_rna_cols_df.columns = ['column']
        wt_rna_cols_df.columns = ['column']

        new = snp_rna_cols_df["column"].str.split("__", n = 1, expand = True) 
        new_wt = wt_rna_cols_df["column"].str.split("__", n = 1, expand = True) 

        snp_rna_cols_df["barc"]= new[1] 
        wt_rna_cols_df["barc"]= new[1]

        ## subset barcodes 
        snp_rna_cols_df = snp_rna_cols_df[snp_rna_cols_df['barc'].isin(barcodes_snp)]
        wt_rna_cols_df = wt_rna_cols_df[wt_rna_cols_df['barc'].isin(barcodes_wt)]  

        cols_snp = ["element"]+ list(random_snp)
        cols_wt = ["element"]+ list(random_wt)
        
        snp_sub_dna = dna_counts_CM_all[dna_counts_CM_all["element"] == seq]
        snp_sub_dna = snp_sub_dna[cols_snp]
        wt_sub_dna = dna_counts_CM_all[dna_counts_CM_all["element"] == seq]
        wt_sub_dna = wt_sub_dna[cols_wt]

        cols_snp_rna = ["element"]+ list(snp_rna_cols_df['column'])
        cols_wt_rna = ["element"]+ list(wt_rna_cols_df['column'])        
        
        snp_sub_rna = rna_counts_CM_all[rna_counts_CM_all["element"] == seq]
        snp_sub_rna = snp_sub_rna[cols_snp_rna]
        wt_sub_rna = rna_counts_CM_all[rna_counts_CM_all["element"] == seq]
        wt_sub_rna = wt_sub_rna[cols_wt_rna]

        snp_rna_cols.extend(["%s___seq:SNP" % x for x in snp_sub_rna.columns if x != "element" ])
        wt_rna_cols.extend(["%s___seq:WT" % x for x in wt_sub_rna.columns if x != "element"])

        snp_dna_cols.extend(["%s___seq:SNP" % x for x in snp_sub_dna.columns if x != "element" ])
        wt_dna_cols.extend(["%s___seq:WT" % x for x in wt_sub_dna.columns if x != "element" ])

        snp_sub_dna.columns = snp_dna_cols
        wt_sub_dna.columns = wt_dna_cols
        snp_sub_rna.columns = snp_rna_cols
        wt_sub_rna.columns = wt_rna_cols

                # add comp_id to each df
        comp_id = "CONTROL:%s__SAMP_PAIR:%s" % ((i+1), (j+1))
        print(comp_id)
        snp_sub_dna["comp_id"] = comp_id
        wt_sub_dna["comp_id"] = comp_id
        snp_sub_rna["comp_id"] = comp_id
        wt_sub_rna["comp_id"] = comp_id

                # merge each df into 1
        snp_sub_dna.drop("element", axis=1, inplace=True)
        wt_sub_dna.drop("element", axis=1, inplace=True)
        snp_sub_rna.drop("element", axis=1, inplace=True)
        wt_sub_rna.drop("element", axis=1, inplace=True)

        sub_dna = snp_sub_dna.merge(wt_sub_dna, on="comp_id")
        sub_rna = snp_sub_rna.merge(wt_sub_rna, on="comp_id")

                # append
        neg_ctrls_dna = neg_ctrls_dna.append(sub_dna)
        neg_ctrls_rna = neg_ctrls_rna.append(sub_rna)

ctrl #: 1
...samp pair #: 1
CONTROL:1__SAMP_PAIR:1
CONTROL:1__SAMP_PAIR:2
CONTROL:1__SAMP_PAIR:3
ctrl #: 2
...samp pair #: 1
CONTROL:2__SAMP_PAIR:1
CONTROL:2__SAMP_PAIR:2
CONTROL:2__SAMP_PAIR:3
ctrl #: 3
...samp pair #: 1
CONTROL:3__SAMP_PAIR:1
CONTROL:3__SAMP_PAIR:2
CONTROL:3__SAMP_PAIR:3
ctrl #: 4
...samp pair #: 1
CONTROL:4__SAMP_PAIR:1
CONTROL:4__SAMP_PAIR:2
CONTROL:4__SAMP_PAIR:3
ctrl #: 5
...samp pair #: 1
CONTROL:5__SAMP_PAIR:1
CONTROL:5__SAMP_PAIR:2
CONTROL:5__SAMP_PAIR:3
ctrl #: 6
...samp pair #: 1
CONTROL:6__SAMP_PAIR:1
CONTROL:6__SAMP_PAIR:2
CONTROL:6__SAMP_PAIR:3
ctrl #: 7
...samp pair #: 1
CONTROL:7__SAMP_PAIR:1
CONTROL:7__SAMP_PAIR:2
CONTROL:7__SAMP_PAIR:3
ctrl #: 8
...samp pair #: 1
CONTROL:8__SAMP_PAIR:1
CONTROL:8__SAMP_PAIR:2
CONTROL:8__SAMP_PAIR:3
ctrl #: 9
...samp pair #: 1
CONTROL:9__SAMP_PAIR:1
CONTROL:9__SAMP_PAIR:2
CONTROL:9__SAMP_PAIR:3
ctrl #: 10
...samp pair #: 1
CONTROL:10__SAMP_PAIR:1
CONTROL:10__SAMP_PAIR:2
CONTROL:10__SAMP_PAIR:3
ctrl #: 11
...samp pair #: 1
CONTROL:11__SAMP_PAIR:1
CONTROL:11__SAMP_PAIR:2
CONTROL:11__SAMP_PAIR:3
ctrl #: 12
...samp pair #: 1
CONTROL:12__SAMP_PAIR:1
CONTROL:12__SAMP_PAIR:2
CONTROL:12__SAMP_PAIR:3
ctrl #: 13
...samp pair #: 1
CONTROL:13__SAMP_PAIR:1
CONTROL:13__SAMP_PAIR:2
CONTROL:13__SAMP_PAIR:3
ctrl #: 14
...samp pair #: 1
CONTROL:14__SAMP_PAIR:1
CONTROL:14__SAMP_PAIR:2
CONTROL:14__SAMP_PAIR:3
ctrl #: 15
...samp pair #: 1
CONTROL:15__SAMP_PAIR:1
CONTROL:15__SAMP_PAIR:2
CONTROL:15__SAMP_PAIR:3
ctrl #: 16
...samp pair #: 1
CONTROL:16__SAMP_PAIR:1
CONTROL:16__SAMP_PAIR:2
CONTROL:16__SAMP_PAIR:3
ctrl #: 17
...samp pair #: 1
CONTROL:17__SAMP_PAIR:1
CONTROL:17__SAMP_PAIR:2
CONTROL:17__SAMP_PAIR:3
ctrl #: 18
...samp pair #: 1
CONTROL:18__SAMP_PAIR:1
CONTROL:18__SAMP_PAIR:2
CONTROL:18__SAMP_PAIR:3
ctrl #: 19
...samp pair #: 1
CONTROL:19__SAMP_PAIR:1
CONTROL:19__SAMP_PAIR:2
CONTROL:19__SAMP_PAIR:3
ctrl #: 20
...samp pair #: 1
CONTROL:20__SAMP_PAIR:1
CONTROL:20__SAMP_PAIR:2
CONTROL:20__SAMP_PAIR:3
ctrl #: 21
...samp pair #: 1
CONTROL:21__SAMP_PAIR:1
CONTROL:21__SAMP_PAIR:2
CONTROL:21__SAMP_PAIR:3
ctrl #: 22
...samp pair #: 1
CONTROL:22__SAMP_PAIR:1
CONTROL:22__SAMP_PAIR:2
CONTROL:22__SAMP_PAIR:3
ctrl #: 23
...samp pair #: 1
CONTROL:23__SAMP_PAIR:1
CONTROL:23__SAMP_PAIR:2
CONTROL:23__SAMP_PAIR:3
ctrl #: 24
...samp pair #: 1
CONTROL:24__SAMP_PAIR:1
CONTROL:24__SAMP_PAIR:2
CONTROL:24__SAMP_PAIR:3
ctrl #: 25
...samp pair #: 1
CONTROL:25__SAMP_PAIR:1
CONTROL:25__SAMP_PAIR:2
CONTROL:25__SAMP_PAIR:3
ctrl #: 26
...samp pair #: 1
CONTROL:26__SAMP_PAIR:1
CONTROL:26__SAMP_PAIR:2
CONTROL:26__SAMP_PAIR:3
ctrl #: 27
...samp pair #: 1
CONTROL:27__SAMP_PAIR:1
CONTROL:27__SAMP_PAIR:2
CONTROL:27__SAMP_PAIR:3
ctrl #: 28
...samp pair #: 1
CONTROL:28__SAMP_PAIR:1
CONTROL:28__SAMP_PAIR:2
CONTROL:28__SAMP_PAIR:3
ctrl #: 29
...samp pair #: 1
CONTROL:29__SAMP_PAIR:1
CONTROL:29__SAMP_PAIR:2
CONTROL:29__SAMP_PAIR:3
ctrl #: 30
...samp pair #: 1
CONTROL:30__SAMP_PAIR:1
CONTROL:30__SAMP_PAIR:2
CONTROL:30__SAMP_PAIR:3
ctrl #: 31
...samp pair #: 1
CONTROL:31__SAMP_PAIR:1
CONTROL:31__SAMP_PAIR:2
CONTROL:31__SAMP_PAIR:3
ctrl #: 32
...samp pair #: 1
CONTROL:32__SAMP_PAIR:1
CONTROL:32__SAMP_PAIR:2
CONTROL:32__SAMP_PAIR:3
ctrl #: 33
...samp pair #: 1
CONTROL:33__SAMP_PAIR:1
CONTROL:33__SAMP_PAIR:2
CONTROL:33__SAMP_PAIR:3
ctrl #: 34
...samp pair #: 1
CONTROL:34__SAMP_PAIR:1
CONTROL:34__SAMP_PAIR:2
CONTROL:34__SAMP_PAIR:3
ctrl #: 35
...samp pair #: 1
CONTROL:35__SAMP_PAIR:1
CONTROL:35__SAMP_PAIR:2
CONTROL:35__SAMP_PAIR:3
ctrl #: 36
...samp pair #: 1
CONTROL:36__SAMP_PAIR:1
CONTROL:36__SAMP_PAIR:2
CONTROL:36__SAMP_PAIR:3
ctrl #: 37
...samp pair #: 1
CONTROL:37__SAMP_PAIR:1
CONTROL:37__SAMP_PAIR:2
CONTROL:37__SAMP_PAIR:3
ctrl #: 38
...samp pair #: 1
CONTROL:38__SAMP_PAIR:1
CONTROL:38__SAMP_PAIR:2
CONTROL:38__SAMP_PAIR:3
ctrl #: 39
...samp pair #: 1
CONTROL:39__SAMP_PAIR:1
CONTROL:39__SAMP_PAIR:2
CONTROL:39__SAMP_PAIR:3
ctrl #: 40
...samp pair #: 1
CONTROL:40__SAMP_PAIR:1
CONTROL:40__SAMP_PAIR:2
CONTROL:40__SAMP_PAIR:3
ctrl #: 41
...samp pair #: 1
CONTROL:41__SAMP_PAIR:1
CONTROL:41__SAMP_PAIR:2
CONTROL:41__SAMP_PAIR:3
ctrl #: 42
...samp pair #: 1
CONTROL:42__SAMP_PAIR:1
CONTROL:42__SAMP_PAIR:2
CONTROL:42__SAMP_PAIR:3

In [97]:
all_dna = dna_map_seqs.append(neg_ctrls_dna)
all_dna.set_index("comp_id", inplace=True)
len(all_dna)

194

In [98]:
all_rna = rna_map_seqs.append(neg_ctrls_rna)
all_rna.set_index("comp_id", inplace=True)
len(all_rna)

194

In [99]:
all_rna.sample(5)

,samp:CM_rep1__barc:1___seq:SNP,samp:CM_rep1__barc:10___seq:SNP,samp:CM_rep1__barc:11___seq:SNP,samp:CM_rep1__barc:12___seq:SNP,samp:CM_rep1__barc:13___seq:SNP,samp:CM_rep1__barc:14___seq:SNP,samp:CM_rep1__barc:15___seq:SNP,samp:CM_rep1__barc:16___seq:SNP,samp:CM_rep1__barc:17___seq:SNP,samp:CM_rep1__barc:18___seq:SNP,...,samp:CM_rep1__barc:75___seq:WT,samp:CM_rep2__barc:75___seq:WT,samp:CM_rep3__barc:75___seq:WT,samp:CM_rep4__barc:75___seq:WT,samp:CM_rep5__barc:75___seq:WT,samp:CM_rep1__barc:32___seq:SNP,samp:CM_rep2__barc:32___seq:SNP,samp:CM_rep3__barc:32___seq:SNP,samp:CM_rep4__barc:32___seq:SNP,samp:CM_rep5__barc:32___seq:SNP
comp_id,,,,,,,,,,,,,,,,,,,,,
CONTROL:3__SAMP_PAIR:1,0.0,NaN,115.0,NaN,NaN,89.0,NaN,NaN,NaN,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CONTROL:16__SAMP_PAIR:2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,270.0,253.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CONTROL:27__SAMP_PAIR:1,NaN,NaN,NaN,1.0,NaN,12.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,90.0,99.0,78.0,76.0,67.0
CONTROL:32__SAMP_PAIR:2,NaN,NaN,268.0,NaN,168.0,NaN,NaN,NaN,76.0,137.0,...,259.0,195.0,231.0,163.0,179.0,68.0,55.0,69.0,51.0,72.0
4690__WILDTYPE_SNP_INDIV,56.0,96.0,33.0,10.0,0.0,45.0,96.0,0.0,16.0,76.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
all_rna.columns

Index(['samp:CM_rep1__barc:1___seq:SNP', 'samp:CM_rep1__barc:10___seq:SNP',
       'samp:CM_rep1__barc:11___seq:SNP', 'samp:CM_rep1__barc:12___seq:SNP',
       'samp:CM_rep1__barc:13___seq:SNP', 'samp:CM_rep1__barc:14___seq:SNP',
       'samp:CM_rep1__barc:15___seq:SNP', 'samp:CM_rep1__barc:16___seq:SNP',
       'samp:CM_rep1__barc:17___seq:SNP', 'samp:CM_rep1__barc:18___seq:SNP',
       ...
       'samp:CM_rep1__barc:75___seq:WT', 'samp:CM_rep2__barc:75___seq:WT',
       'samp:CM_rep3__barc:75___seq:WT', 'samp:CM_rep4__barc:75___seq:WT',
       'samp:CM_rep5__barc:75___seq:WT', 'samp:CM_rep1__barc:32___seq:SNP',
       'samp:CM_rep2__barc:32___seq:SNP', 'samp:CM_rep3__barc:32___seq:SNP',
       'samp:CM_rep4__barc:32___seq:SNP', 'samp:CM_rep5__barc:32___seq:SNP'],
      dtype='object', length=1002)

In [44]:
all_rna.drop(['element___seq:WT'],axis=1, inplace=True)
all_dna.drop(['element___seq:WT'],axis=1, inplace=True)
all_rna.head()

,samp:CM_rep1__barc:10___seq:SNP,samp:CM_rep1__barc:10___seq:WT,samp:CM_rep1__barc:11___seq:SNP,samp:CM_rep1__barc:11___seq:WT,samp:CM_rep1__barc:12___seq:SNP,samp:CM_rep1__barc:12___seq:WT,samp:CM_rep1__barc:13___seq:SNP,samp:CM_rep1__barc:13___seq:WT,samp:CM_rep1__barc:14___seq:SNP,samp:CM_rep1__barc:14___seq:WT,...,samp:CM_rep5__barc:6___seq:SNP,samp:CM_rep5__barc:6___seq:WT,samp:CM_rep5__barc:7___seq:SNP,samp:CM_rep5__barc:7___seq:WT,samp:CM_rep5__barc:8___seq:SNP,samp:CM_rep5__barc:8___seq:WT,samp:CM_rep5__barc:9___seq:SNP,samp:CM_rep5__barc:9___seq:WT,tile_id___seq:WT,tile_type___seq:WT
comp_id,,,,,,,,,,,,,,,,,,,,,
4670__WILDTYPE_SNP_INDIV,126.0,206.0,90.0,0.0,280.0,88.0,9.0,48.0,92.0,246.0,...,277.0,112.0,118.0,9.0,415.0,145.0,72.0,11.0,NaN,WILDTYPE_BUT_HAS_SNP
4707__WILDTYPE_SNP_INDIV,0.0,23.0,8.0,8.0,0.0,0.0,25.0,29.0,0.0,52.0,...,0.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,NaN,WILDTYPE_BUT_HAS_SNP
4695__WILDTYPE_SNP_INDIV,15.0,0.0,31.0,0.0,3.0,0.0,0.0,15.0,8.0,0.0,...,11.0,0.0,22.0,9.0,0.0,5.0,0.0,1.0,NaN,WILDTYPE_BUT_HAS_SNP
4651__WILDTYPE_SNP_INDIV,883.0,625.0,324.0,771.0,470.0,27.0,614.0,43.0,313.0,0.0,...,437.0,40.0,298.0,870.0,500.0,197.0,930.0,806.0,NaN,WILDTYPE_BUT_HAS_SNP
4655__WILDTYPE_SNP_INDIV,17.0,34.0,73.0,0.0,71.0,82.0,0.0,0.0,20.0,5.0,...,10.0,18.0,2.0,1.0,53.0,26.0,7.0,51.0,NaN,WILDTYPE_BUT_HAS_SNP

In [45]:
all_rna.drop(['tile_type___seq:WT','tile_id___seq:WT'],axis=1, inplace=True)
all_dna.drop(['tile_type___seq:WT','tile_id___seq:WT'],axis=1, inplace=True)
all_rna.head()

,samp:CM_rep1__barc:10___seq:SNP,samp:CM_rep1__barc:10___seq:WT,samp:CM_rep1__barc:11___seq:SNP,samp:CM_rep1__barc:11___seq:WT,samp:CM_rep1__barc:12___seq:SNP,samp:CM_rep1__barc:12___seq:WT,samp:CM_rep1__barc:13___seq:SNP,samp:CM_rep1__barc:13___seq:WT,samp:CM_rep1__barc:14___seq:SNP,samp:CM_rep1__barc:14___seq:WT,...,samp:CM_rep5__barc:5___seq:SNP,samp:CM_rep5__barc:5___seq:WT,samp:CM_rep5__barc:6___seq:SNP,samp:CM_rep5__barc:6___seq:WT,samp:CM_rep5__barc:7___seq:SNP,samp:CM_rep5__barc:7___seq:WT,samp:CM_rep5__barc:8___seq:SNP,samp:CM_rep5__barc:8___seq:WT,samp:CM_rep5__barc:9___seq:SNP,samp:CM_rep5__barc:9___seq:WT
comp_id,,,,,,,,,,,,,,,,,,,,,
4670__WILDTYPE_SNP_INDIV,126.0,206.0,90.0,0.0,280.0,88.0,9.0,48.0,92.0,246.0,...,137.0,11.0,277.0,112.0,118.0,9.0,415.0,145.0,72.0,11.0
4707__WILDTYPE_SNP_INDIV,0.0,23.0,8.0,8.0,0.0,0.0,25.0,29.0,0.0,52.0,...,0.0,5.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0
4695__WILDTYPE_SNP_INDIV,15.0,0.0,31.0,0.0,3.0,0.0,0.0,15.0,8.0,0.0,...,30.0,18.0,11.0,0.0,22.0,9.0,0.0,5.0,0.0,1.0
4651__WILDTYPE_SNP_INDIV,883.0,625.0,324.0,771.0,470.0,27.0,614.0,43.0,313.0,0.0,...,59.0,193.0,437.0,40.0,298.0,870.0,500.0,197.0,930.0,806.0
4655__WILDTYPE_SNP_INDIV,17.0,34.0,73.0,0.0,71.0,82.0,0.0,0.0,20.0,5.0,...,2.0,44.0,10.0,18.0,2.0,1.0,53.0,26.0,7.0,51.0

In [46]:
all_dna_cols = all_dna.columns
all_rna_cols = all_rna.columns

In [47]:
all_dna_cols

Index(['samp:dna_1__barc:10___seq:SNP', 'samp:dna_1__barc:10___seq:WT',
       'samp:dna_1__barc:11___seq:SNP', 'samp:dna_1__barc:11___seq:WT',
       'samp:dna_1__barc:12___seq:SNP', 'samp:dna_1__barc:12___seq:WT',
       'samp:dna_1__barc:13___seq:SNP', 'samp:dna_1__barc:13___seq:WT',
       'samp:dna_1__barc:14___seq:SNP', 'samp:dna_1__barc:14___seq:WT',
       'samp:dna_1__barc:15___seq:SNP', 'samp:dna_1__barc:15___seq:WT',
       'samp:dna_1__barc:16___seq:SNP', 'samp:dna_1__barc:16___seq:WT',
       'samp:dna_1__barc:17___seq:SNP', 'samp:dna_1__barc:17___seq:WT',
       'samp:dna_1__barc:18___seq:SNP', 'samp:dna_1__barc:18___seq:WT',
       'samp:dna_1__barc:19___seq:SNP', 'samp:dna_1__barc:19___seq:WT',
       'samp:dna_1__barc:1___seq:SNP', 'samp:dna_1__barc:1___seq:WT',
       'samp:dna_1__barc:20___seq:SNP', 'samp:dna_1__barc:20___seq:WT',
       'samp:dna_1__barc:21___seq:SNP', 'samp:dna_1__barc:21___seq:WT',
       'samp:dna_1__barc:22___seq:SNP', 'samp:dna_1__barc:22___seq:WT',
       'samp:dna_1__barc:23___seq:SNP', 'samp:dna_1__barc:23___seq:WT',
       'samp:dna_1__barc:24___seq:SNP', 'samp:dna_1__barc:24___seq:WT',
       'samp:dna_1__barc:25___seq:SNP', 'samp:dna_1__barc:25___seq:WT',
       'samp:dna_1__barc:2___seq:SNP', 'samp:dna_1__barc:2___seq:WT',
       'samp:dna_1__barc:3___seq:SNP', 'samp:dna_1__barc:3___seq:WT',
       'samp:dna_1__barc:4___seq:SNP', 'samp:dna_1__barc:4___seq:WT',
       'samp:dna_1__barc:5___seq:SNP', 'samp:dna_1__barc:5___seq:WT',
       'samp:dna_1__barc:6___seq:SNP', 'samp:dna_1__barc:6___seq:WT',
       'samp:dna_1__barc:7___seq:SNP', 'samp:dna_1__barc:7___seq:WT',
       'samp:dna_1__barc:8___seq:SNP', 'samp:dna_1__barc:8___seq:WT',
       'samp:dna_1__barc:9___seq:SNP', 'samp:dna_1__barc:9___seq:WT'],
      dtype='object')

## 7. make annotation files

In [101]:
all_rna.drop(['element___seq:WT'],axis=1, inplace=True)
all_dna.drop(['element___seq:WT'],axis=1, inplace=True)
all_rna.head()

,samp:CM_rep1__barc:1___seq:SNP,samp:CM_rep1__barc:10___seq:SNP,samp:CM_rep1__barc:11___seq:SNP,samp:CM_rep1__barc:12___seq:SNP,samp:CM_rep1__barc:13___seq:SNP,samp:CM_rep1__barc:14___seq:SNP,samp:CM_rep1__barc:15___seq:SNP,samp:CM_rep1__barc:16___seq:SNP,samp:CM_rep1__barc:17___seq:SNP,samp:CM_rep1__barc:18___seq:SNP,...,samp:CM_rep1__barc:75___seq:WT,samp:CM_rep2__barc:75___seq:WT,samp:CM_rep3__barc:75___seq:WT,samp:CM_rep4__barc:75___seq:WT,samp:CM_rep5__barc:75___seq:WT,samp:CM_rep1__barc:32___seq:SNP,samp:CM_rep2__barc:32___seq:SNP,samp:CM_rep3__barc:32___seq:SNP,samp:CM_rep4__barc:32___seq:SNP,samp:CM_rep5__barc:32___seq:SNP
comp_id,,,,,,,,,,,,,,,,,,,,,
4670__WILDTYPE_SNP_INDIV,14.0,126.0,90.0,280.0,9.0,92.0,220.0,428.0,144.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4707__WILDTYPE_SNP_INDIV,0.0,0.0,8.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4695__WILDTYPE_SNP_INDIV,2.0,15.0,31.0,3.0,0.0,8.0,0.0,0.0,0.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4651__WILDTYPE_SNP_INDIV,135.0,883.0,324.0,470.0,614.0,313.0,659.0,493.0,225.0,1223.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4655__WILDTYPE_SNP_INDIV,7.0,17.0,73.0,71.0,0.0,20.0,0.0,46.0,31.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
all_rna.drop(['tile_type___seq:WT'],axis=1, inplace=True)
all_dna.drop(['tile_type___seq:WT'],axis=1, inplace=True)
all_rna.head()

,samp:CM_rep1__barc:1___seq:SNP,samp:CM_rep1__barc:10___seq:SNP,samp:CM_rep1__barc:11___seq:SNP,samp:CM_rep1__barc:12___seq:SNP,samp:CM_rep1__barc:13___seq:SNP,samp:CM_rep1__barc:14___seq:SNP,samp:CM_rep1__barc:15___seq:SNP,samp:CM_rep1__barc:16___seq:SNP,samp:CM_rep1__barc:17___seq:SNP,samp:CM_rep1__barc:18___seq:SNP,...,samp:CM_rep1__barc:75___seq:WT,samp:CM_rep2__barc:75___seq:WT,samp:CM_rep3__barc:75___seq:WT,samp:CM_rep4__barc:75___seq:WT,samp:CM_rep5__barc:75___seq:WT,samp:CM_rep1__barc:32___seq:SNP,samp:CM_rep2__barc:32___seq:SNP,samp:CM_rep3__barc:32___seq:SNP,samp:CM_rep4__barc:32___seq:SNP,samp:CM_rep5__barc:32___seq:SNP
comp_id,,,,,,,,,,,,,,,,,,,,,
4670__WILDTYPE_SNP_INDIV,14.0,126.0,90.0,280.0,9.0,92.0,220.0,428.0,144.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4707__WILDTYPE_SNP_INDIV,0.0,0.0,8.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4695__WILDTYPE_SNP_INDIV,2.0,15.0,31.0,3.0,0.0,8.0,0.0,0.0,0.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4651__WILDTYPE_SNP_INDIV,135.0,883.0,324.0,470.0,614.0,313.0,659.0,493.0,225.0,1223.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4655__WILDTYPE_SNP_INDIV,7.0,17.0,73.0,71.0,0.0,20.0,0.0,46.0,31.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
all_dna_cols = all_dna.columns
all_rna_cols = all_rna.columns

In [104]:
all_rna_cols

Index(['samp:CM_rep1__barc:1___seq:SNP', 'samp:CM_rep1__barc:10___seq:SNP',
       'samp:CM_rep1__barc:11___seq:SNP', 'samp:CM_rep1__barc:12___seq:SNP',
       'samp:CM_rep1__barc:13___seq:SNP', 'samp:CM_rep1__barc:14___seq:SNP',
       'samp:CM_rep1__barc:15___seq:SNP', 'samp:CM_rep1__barc:16___seq:SNP',
       'samp:CM_rep1__barc:17___seq:SNP', 'samp:CM_rep1__barc:18___seq:SNP',
       ...
       'samp:CM_rep1__barc:75___seq:WT', 'samp:CM_rep2__barc:75___seq:WT',
       'samp:CM_rep3__barc:75___seq:WT', 'samp:CM_rep4__barc:75___seq:WT',
       'samp:CM_rep5__barc:75___seq:WT', 'samp:CM_rep1__barc:32___seq:SNP',
       'samp:CM_rep2__barc:32___seq:SNP', 'samp:CM_rep3__barc:32___seq:SNP',
       'samp:CM_rep4__barc:32___seq:SNP', 'samp:CM_rep5__barc:32___seq:SNP'],
      dtype='object', length=1000)

In [105]:
dna_col_ann = {}
rna_col_ann = {}

for cols, ann in zip([all_dna_cols, all_rna_cols], 
                     [dna_col_ann, rna_col_ann]):
    for col in cols:
        print(col)
        if col == "comp_id":
            continue
        cond = col.split(":")[1].split("_")[0]
        barc = col.split(":")[2].split("__")[0]
        seq = col.split(":")[-1]
        ann[col] = {"condition": cond, "barcode": barc, "seq": seq}

dna_col_ann = pd.DataFrame.from_dict(dna_col_ann, orient="index")
rna_col_ann = pd.DataFrame.from_dict(rna_col_ann, orient="index")
rna_col_ann.sample(5)

samp:dna_1__barc:1___seq:SNP
samp:dna_1__barc:10___seq:SNP
samp:dna_1__barc:11___seq:SNP
samp:dna_1__barc:12___seq:SNP
samp:dna_1__barc:13___seq:SNP
samp:dna_1__barc:14___seq:SNP
samp:dna_1__barc:15___seq:SNP
samp:dna_1__barc:16___seq:SNP
samp:dna_1__barc:17___seq:SNP
samp:dna_1__barc:18___seq:SNP
samp:dna_1__barc:19___seq:SNP
samp:dna_1__barc:2___seq:SNP
samp:dna_1__barc:20___seq:SNP
samp:dna_1__barc:21___seq:SNP
samp:dna_1__barc:22___seq:SNP
samp:dna_1__barc:23___seq:SNP
samp:dna_1__barc:24___seq:SNP
samp:dna_1__barc:25___seq:SNP
samp:dna_1__barc:3___seq:SNP
samp:dna_1__barc:4___seq:SNP
samp:dna_1__barc:5___seq:SNP
samp:dna_1__barc:6___seq:SNP
samp:dna_1__barc:7___seq:SNP
samp:dna_1__barc:8___seq:SNP
samp:dna_1__barc:9___seq:SNP
samp:dna_1__barc:1___seq:WT
samp:dna_1__barc:10___seq:WT
samp:dna_1__barc:11___seq:WT
samp:dna_1__barc:12___seq:WT
samp:dna_1__barc:13___seq:WT
samp:dna_1__barc:14___seq:WT
samp:dna_1__barc:15___seq:WT
samp:dna_1__barc:16___seq:WT
samp:dna_1__barc:17___seq:WT
samp:dna_1__barc:18___seq:WT
samp:dna_1__barc:19___seq:WT
samp:dna_1__barc:2___seq:WT
samp:dna_1__barc:20___seq:WT
samp:dna_1__barc:21___seq:WT
samp:dna_1__barc:22___seq:WT
samp:dna_1__barc:23___seq:WT
samp:dna_1__barc:24___seq:WT
samp:dna_1__barc:25___seq:WT
samp:dna_1__barc:3___seq:WT
samp:dna_1__barc:4___seq:WT
samp:dna_1__barc:5___seq:WT
samp:dna_1__barc:6___seq:WT
samp:dna_1__barc:7___seq:WT
samp:dna_1__barc:8___seq:WT
samp:dna_1__barc:9___seq:WT
samp:dna_1__barc:64___seq:SNP
samp:dna_1__barc:62___seq:SNP
samp:dna_1__barc:44___seq:SNP
samp:dna_1__barc:74___seq:SNP
samp:dna_1__barc:60___seq:SNP
samp:dna_1__barc:98___seq:SNP
samp:dna_1__barc:93___seq:SNP
samp:dna_1__barc:58___seq:SNP
samp:dna_1__barc:77___seq:SNP
samp:dna_1__barc:49___seq:SNP
samp:dna_1__barc:27___seq:SNP
samp:dna_1__barc:72___seq:SNP
samp:dna_1__barc:81___seq:SNP
samp:dna_1__barc:39___seq:SNP
samp:dna_1__barc:56___seq:SNP
samp:dna_1__barc:79___seq:SNP
samp:dna_1__barc:65___seq:SNP
samp:dna_1__barc:49___seq:WT
samp:dna_1__barc:52___seq:WT
samp:dna_1__barc:37___seq:WT
samp:dna_1__barc:43___seq:WT
samp:dna_1__barc:30___seq:WT
samp:dna_1__barc:51___seq:WT
samp:dna_1__barc:99___seq:WT
samp:dna_1__barc:62___seq:WT
samp:dna_1__barc:66___seq:WT
samp:dna_1__barc:73___seq:WT
samp:dna_1__barc:53___seq:WT
samp:dna_1__barc:68___seq:WT
samp:dna_1__barc:100___seq:WT
samp:dna_1__barc:89___seq:WT
samp:dna_1__barc:58___seq:WT
samp:dna_1__barc:88___seq:WT
samp:dna_1__barc:64___seq:WT
samp:dna_1__barc:92___seq:WT
samp:dna_1__barc:33___seq:WT
samp:dna_1__barc:36___seq:SNP
samp:dna_1__barc:89___seq:SNP
samp:dna_1__barc:43___seq:SNP
samp:dna_1__barc:59___seq:SNP
samp:dna_1__barc:37___seq:SNP
samp:dna_1__barc:63___seq:SNP
samp:dna_1__barc:33___seq:SNP
samp:dna_1__barc:80___seq:SNP
samp:dna_1__barc:54___seq:SNP
samp:dna_1__barc:75___seq:SNP
samp:dna_1__barc:97___seq:SNP
samp:dna_1__barc:71___seq:SNP
samp:dna_1__barc:47___seq:SNP
samp:dna_1__barc:53___seq:SNP
samp:dna_1__barc:31___seq:SNP
samp:dna_1__barc:95___seq:SNP
samp:dna_1__barc:78___seq:SNP
samp:dna_1__barc:100___seq:SNP
samp:dna_1__barc:41___seq:WT
samp:dna_1__barc:63___seq:WT
samp:dna_1__barc:44___seq:WT
samp:dna_1__barc:46___seq:WT
samp:dna_1__barc:57___seq:WT
samp:dna_1__barc:81___seq:WT
samp:dna_1__barc:36___seq:WT
samp:dna_1__barc:71___seq:WT
samp:dna_1__barc:40___seq:WT
samp:dna_1__barc:56___seq:WT
samp:dna_1__barc:31___seq:WT
samp:dna_1__barc:67___seq:WT
samp:dna_1__barc:86___seq:WT
samp:dna_1__barc:91___seq:WT
samp:dna_1__barc:28___seq:WT
samp:dna_1__barc:96___seq:WT
samp:dna_1__barc:26___seq:SNP
samp:dna_1__barc:68___seq:SNP
samp:dna_1__barc:28___seq:SNP
samp:dna_1__barc:40___seq:SNP
samp:dna_1__barc:90___seq:SNP
samp:dna_1__barc:86___seq:SNP
samp:dna_1__barc:91___seq:SNP
samp:dna_1__barc:55___seq:SNP
samp:dna_1__barc:87___seq:SNP
samp:dna_1__barc:52___seq:SNP
samp:dna_1__barc:82___seq:SNP
samp:dna_1__barc:93___seq:WT
samp:dna_1__barc:60___seq:WT
samp:dna_1__barc:59___seq:WT
samp:dna_1__barc:76___seq:WT
samp:dna_1__barc:84___seq:WT
samp:dna_1__barc:79___seq:WT
samp:dna_1__barc:39___seq:WT
samp:dna_1__barc:95___seq:WT
samp:dna_1__barc:61___seq:WT
samp:dna_1__barc:35___seq:WT
samp:dna_1__barc:54___seq:WT
samp:dna_1__barc:80___seq:WT
samp:dna_1__barc:35___seq:SNP
samp:dna_1__barc:73___seq:SNP
samp:dna_1__barc:57___seq:SNP
samp:dna_1__barc:41___seq:SNP
samp:dna_1__barc:84___seq:SNP
samp:dna_1__barc:30___seq:SNP
samp:dna_1__barc:85___seq:SNP
samp:dna_1__barc:92___seq:SNP
samp:dna_1__barc:76___seq:SNP
samp:dna_1__barc:66___seq:SNP
samp:dna_1__barc:77___seq:WT
samp:dna_1__barc:47___seq:WT
samp:dna_1__barc:97___seq:WT
samp:dna_1__barc:26___seq:WT
samp:dna_1__barc:94___seq:WT
samp:dna_1__barc:42___seq:WT
samp:dna_1__barc:96___seq:SNP
samp:dna_1__barc:34___seq:SNP
samp:dna_1__barc:69___seq:SNP
samp:dna_1__barc:61___seq:SNP
samp:dna_1__barc:38___seq:WT
samp:dna_1__barc:78___seq:WT
samp:dna_1__barc:50___seq:WT
samp:dna_1__barc:48___seq:WT
samp:dna_1__barc:85___seq:WT
samp:dna_1__barc:83___seq:WT
samp:dna_1__barc:83___seq:SNP
samp:dna_1__barc:99___seq:SNP
samp:dna_1__barc:29___seq:SNP
samp:dna_1__barc:46___seq:SNP
samp:dna_1__barc:87___seq:WT
samp:dna_1__barc:70___seq:WT
samp:dna_1__barc:29___seq:WT
samp:dna_1__barc:90___seq:WT
samp:dna_1__barc:65___seq:WT
samp:dna_1__barc:69___seq:WT
samp:dna_1__barc:72___seq:WT
samp:dna_1__barc:32___seq:WT
samp:dna_1__barc:38___seq:SNP
samp:dna_1__barc:88___seq:SNP
samp:dna_1__barc:42___seq:SNP
samp:dna_1__barc:82___seq:WT
samp:dna_1__barc:27___seq:WT
samp:dna_1__barc:74___seq:WT
samp:dna_1__barc:34___seq:WT
samp:dna_1__barc:94___seq:SNP
samp:dna_1__barc:45___seq:SNP
samp:dna_1__barc:50___seq:SNP
samp:dna_1__barc:70___seq:SNP
samp:dna_1__barc:98___seq:WT
samp:dna_1__barc:55___seq:WT
samp:dna_1__barc:67___seq:SNP
samp:dna_1__barc:51___seq:SNP
samp:dna_1__barc:45___seq:WT
samp:dna_1__barc:48___seq:SNP
samp:dna_1__barc:75___seq:WT
samp:dna_1__barc:32___seq:SNP
samp:CM_rep1__barc:1___seq:SNP
samp:CM_rep1__barc:10___seq:SNP
samp:CM_rep1__barc:11___seq:SNP
samp:CM_rep1__barc:12___seq:SNP
samp:CM_rep1__barc:13___seq:SNP
samp:CM_rep1__barc:14___seq:SNP
samp:CM_rep1__barc:15___seq:SNP
samp:CM_rep1__barc:16___seq:SNP
samp:CM_rep1__barc:17___seq:SNP
samp:CM_rep1__barc:18___seq:SNP
samp:CM_rep1__barc:19___seq:SNP
samp:CM_rep1__barc:2___seq:SNP
samp:CM_rep1__barc:20___seq:SNP
samp:CM_rep1__barc:21___seq:SNP
samp:CM_rep1__barc:22___seq:SNP
samp:CM_rep1__barc:23___seq:SNP
samp:CM_rep1__barc:24___seq:SNP
samp:CM_rep1__barc:25___seq:SNP
samp:CM_rep1__barc:3___seq:SNP
samp:CM_rep1__barc:4___seq:SNP
samp:CM_rep1__barc:5___seq:SNP
samp:CM_rep1__barc:6___seq:SNP
samp:CM_rep1__barc:7___seq:SNP
samp:CM_rep1__barc:8___seq:SNP
samp:CM_rep1__barc:9___seq:SNP
samp:CM_rep2__barc:1___seq:SNP
samp:CM_rep2__barc:10___seq:SNP
samp:CM_rep2__barc:11___seq:SNP
samp:CM_rep2__barc:12___seq:SNP
samp:CM_rep2__barc:13___seq:SNP
samp:CM_rep2__barc:14___seq:SNP
samp:CM_rep2__barc:15___seq:SNP
samp:CM_rep2__barc:16___seq:SNP
samp:CM_rep2__barc:17___seq:SNP
samp:CM_rep2__barc:18___seq:SNP
samp:CM_rep2__barc:19___seq:SNP
samp:CM_rep2__barc:2___seq:SNP
samp:CM_rep2__barc:20___seq:SNP
samp:CM_rep2__barc:21___seq:SNP
samp:CM_rep2__barc:22___seq:SNP
samp:CM_rep2__barc:23___seq:SNP
samp:CM_rep2__barc:24___seq:SNP
samp:CM_rep2__barc:25___seq:SNP
samp:CM_rep2__barc:3___seq:SNP
samp:CM_rep2__barc:4___seq:SNP
samp:CM_rep2__barc:5___seq:SNP
samp:CM_rep2__barc:6___seq:SNP
samp:CM_rep2__barc:7___seq:SNP
samp:CM_rep2__barc:8___seq:SNP
samp:CM_rep2__barc:9___seq:SNP
samp:CM_rep3__barc:1___seq:SNP
samp:CM_rep3__barc:10___seq:SNP
samp:CM_rep3__barc:11___seq:SNP
samp:CM_rep3__barc:12___seq:SNP
samp:CM_rep3__barc:13___seq:SNP
samp:CM_rep3__barc:14___seq:SNP
samp:CM_rep3__barc:15___seq:SNP
samp:CM_rep3__barc:16___seq:SNP
samp:CM_rep3__barc:17___seq:SNP
samp:CM_rep3__barc:18___seq:SNP
samp:CM_rep3__barc:19___seq:SNP
samp:CM_rep3__barc:2___seq:SNP
samp:CM_rep3__barc:20___seq:SNP
samp:CM_rep3__barc:21___seq:SNP
samp:CM_rep3__barc:22___seq:SNP
samp:CM_rep3__barc:23___seq:SNP
samp:CM_rep3__barc:24___seq:SNP
samp:CM_rep3__barc:25___seq:SNP
samp:CM_rep3__barc:3___seq:SNP
samp:CM_rep3__barc:4___seq:SNP
samp:CM_rep3__barc:5___seq:SNP
samp:CM_rep3__barc:6___seq:SNP
samp:CM_rep3__barc:7___seq:SNP
samp:CM_rep3__barc:8___seq:SNP
samp:CM_rep3__barc:9___seq:SNP
samp:CM_rep4__barc:1___seq:SNP
samp:CM_rep4__barc:10___seq:SNP
samp:CM_rep4__barc:11___seq:SNP
samp:CM_rep4__barc:12___seq:SNP
samp:CM_rep4__barc:13___seq:SNP
samp:CM_rep4__barc:14___seq:SNP
samp:CM_rep4__barc:15___seq:SNP
samp:CM_rep4__barc:16___seq:SNP
samp:CM_rep4__barc:17___seq:SNP
samp:CM_rep4__barc:18___seq:SNP
samp:CM_rep4__barc:19___seq:SNP
samp:CM_rep4__barc:2___seq:SNP
samp:CM_rep4__barc:20___seq:SNP
samp:CM_rep4__barc:21___seq:SNP
samp:CM_rep4__barc:22___seq:SNP
samp:CM_rep4__barc:23___seq:SNP
samp:CM_rep4__barc:24___seq:SNP
samp:CM_rep4__barc:25___seq:SNP
samp:CM_rep4__barc:3___seq:SNP
samp:CM_rep4__barc:4___seq:SNP
samp:CM_rep4__barc:5___seq:SNP
samp:CM_rep4__barc:6___seq:SNP
samp:CM_rep4__barc:7___seq:SNP
samp:CM_rep4__barc:8___seq:SNP
samp:CM_rep4__barc:9___seq:SNP
samp:CM_rep5__barc:1___seq:SNP
samp:CM_rep5__barc:10___seq:SNP
samp:CM_rep5__barc:11___seq:SNP
samp:CM_rep5__barc:12___seq:SNP
samp:CM_rep5__barc:13___seq:SNP
samp:CM_rep5__barc:14___seq:SNP
samp:CM_rep5__barc:15___seq:SNP
samp:CM_rep5__barc:16___seq:SNP
samp:CM_rep5__barc:17___seq:SNP
samp:CM_rep5__barc:18___seq:SNP
samp:CM_rep5__barc:19___seq:SNP
samp:CM_rep5__barc:2___seq:SNP
samp:CM_rep5__barc:20___seq:SNP
samp:CM_rep5__barc:21___seq:SNP
samp:CM_rep5__barc:22___seq:SNP
samp:CM_rep5__barc:23___seq:SNP
samp:CM_rep5__barc:24___seq:SNP
samp:CM_rep5__barc:25___seq:SNP
samp:CM_rep5__barc:3___seq:SNP
samp:CM_rep5__barc:4___seq:SNP
samp:CM_rep5__barc:5___seq:SNP
samp:CM_rep5__barc:6___seq:SNP
samp:CM_rep5__barc:7___seq:SNP
samp:CM_rep5__barc:8___seq:SNP
samp:CM_rep5__barc:9___seq:SNP
samp:CM_rep1__barc:1___seq:WT
samp:CM_rep1__barc:10___seq:WT
samp:CM_rep1__barc:11___seq:WT
samp:CM_rep1__barc:12___seq:WT
samp:CM_rep1__barc:13___seq:WT
samp:CM_rep1__barc:14___seq:WT
samp:CM_rep1__barc:15___seq:WT
samp:CM_rep1__barc:16___seq:WT
samp:CM_rep1__barc:17___seq:WT
samp:CM_rep1__barc:18___seq:WT
samp:CM_rep1__barc:19___seq:WT
samp:CM_rep1__barc:2___seq:WT
samp:CM_rep1__barc:20___seq:WT
samp:CM_rep1__barc:21___seq:WT
samp:CM_rep1__barc:22___seq:WT
samp:CM_rep1__barc:23___seq:WT
samp:CM_rep1__barc:24___seq:WT
samp:CM_rep1__barc:25___seq:WT
samp:CM_rep1__barc:3___seq:WT
samp:CM_rep1__barc:4___seq:WT
samp:CM_rep1__barc:5___seq:WT
samp:CM_rep1__barc:6___seq:WT
samp:CM_rep1__barc:7___seq:WT
samp:CM_rep1__barc:8___seq:WT
samp:CM_rep1__barc:9___seq:WT
samp:CM_rep2__barc:1___seq:WT
samp:CM_rep2__barc:10___seq:WT
samp:CM_rep2__barc:11___seq:WT
samp:CM_rep2__barc:12___seq:WT
samp:CM_rep2__barc:13___seq:WT
samp:CM_rep2__barc:14___seq:WT
samp:CM_rep2__barc:15___seq:WT
samp:CM_rep2__barc:16___seq:WT
samp:CM_rep2__barc:17___seq:WT
samp:CM_rep2__barc:18___seq:WT
samp:CM_rep2__barc:19___seq:WT
samp:CM_rep2__barc:2___seq:WT
samp:CM_rep2__barc:20___seq:WT
samp:CM_rep2__barc:21___seq:WT
samp:CM_rep2__barc:22___seq:WT
samp:CM_rep2__barc:23___seq:WT
samp:CM_rep2__barc:24___seq:WT
samp:CM_rep2__barc:25___seq:WT
samp:CM_rep2__barc:3___seq:WT
samp:CM_rep2__barc:4___seq:WT
samp:CM_rep2__barc:5___seq:WT
samp:CM_rep2__barc:6___seq:WT
samp:CM_rep2__barc:7___seq:WT
samp:CM_rep2__barc:8___seq:WT
samp:CM_rep2__barc:9___seq:WT
samp:CM_rep3__barc:1___seq:WT
samp:CM_rep3__barc:10___seq:WT
samp:CM_rep3__barc:11___seq:WT
samp:CM_rep3__barc:12___seq:WT
samp:CM_rep3__barc:13___seq:WT
samp:CM_rep3__barc:14___seq:WT
samp:CM_rep3__barc:15___seq:WT
samp:CM_rep3__barc:16___seq:WT
samp:CM_rep3__barc:17___seq:WT
samp:CM_rep3__barc:18___seq:WT
samp:CM_rep3__barc:19___seq:WT
samp:CM_rep3__barc:2___seq:WT
samp:CM_rep3__barc:20___seq:WT
samp:CM_rep3__barc:21___seq:WT
samp:CM_rep3__barc:22___seq:WT
samp:CM_rep3__barc:23___seq:WT
samp:CM_rep3__barc:24___seq:WT
samp:CM_rep3__barc:25___seq:WT
samp:CM_rep3__barc:3___seq:WT
samp:CM_rep3__barc:4___seq:WT
samp:CM_rep3__barc:5___seq:WT
samp:CM_rep3__barc:6___seq:WT
samp:CM_rep3__barc:7___seq:WT
samp:CM_rep3__barc:8___seq:WT
samp:CM_rep3__barc:9___seq:WT
samp:CM_rep4__barc:1___seq:WT
samp:CM_rep4__barc:10___seq:WT
samp:CM_rep4__barc:11___seq:WT
samp:CM_rep4__barc:12___seq:WT
samp:CM_rep4__barc:13___seq:WT
samp:CM_rep4__barc:14___seq:WT
samp:CM_rep4__barc:15___seq:WT
samp:CM_rep4__barc:16___seq:WT
samp:CM_rep4__barc:17___seq:WT
samp:CM_rep4__barc:18___seq:WT
samp:CM_rep4__barc:19___seq:WT
samp:CM_rep4__barc:2___seq:WT
samp:CM_rep4__barc:20___seq:WT
samp:CM_rep4__barc:21___seq:WT
samp:CM_rep4__barc:22___seq:WT
samp:CM_rep4__barc:23___seq:WT
samp:CM_rep4__barc:24___seq:WT
samp:CM_rep4__barc:25___seq:WT
samp:CM_rep4__barc:3___seq:WT
samp:CM_rep4__barc:4___seq:WT
samp:CM_rep4__barc:5___seq:WT
samp:CM_rep4__barc:6___seq:WT
samp:CM_rep4__barc:7___seq:WT
samp:CM_rep4__barc:8___seq:WT
samp:CM_rep4__barc:9___seq:WT
samp:CM_rep5__barc:1___seq:WT
samp:CM_rep5__barc:10___seq:WT
samp:CM_rep5__barc:11___seq:WT
samp:CM_rep5__barc:12___seq:WT
samp:CM_rep5__barc:13___seq:WT
samp:CM_rep5__barc:14___seq:WT
samp:CM_rep5__barc:15___seq:WT
samp:CM_rep5__barc:16___seq:WT
samp:CM_rep5__barc:17___seq:WT
samp:CM_rep5__barc:18___seq:WT
samp:CM_rep5__barc:19___seq:WT
samp:CM_rep5__barc:2___seq:WT
samp:CM_rep5__barc:20___seq:WT
samp:CM_rep5__barc:21___seq:WT
samp:CM_rep5__barc:22___seq:WT
samp:CM_rep5__barc:23___seq:WT
samp:CM_rep5__barc:24___seq:WT
samp:CM_rep5__barc:25___seq:WT
samp:CM_rep5__barc:3___seq:WT
samp:CM_rep5__barc:4___seq:WT
samp:CM_rep5__barc:5___seq:WT
samp:CM_rep5__barc:6___seq:WT
samp:CM_rep5__barc:7___seq:WT
samp:CM_rep5__barc:8___seq:WT
samp:CM_rep5__barc:9___seq:WT
samp:CM_rep1__barc:27___seq:SNP
samp:CM_rep1__barc:39___seq:SNP
samp:CM_rep1__barc:44___seq:SNP
samp:CM_rep1__barc:49___seq:SNP
samp:CM_rep1__barc:56___seq:SNP
samp:CM_rep1__barc:58___seq:SNP
samp:CM_rep1__barc:60___seq:SNP
samp:CM_rep1__barc:62___seq:SNP
samp:CM_rep1__barc:64___seq:SNP
samp:CM_rep1__barc:65___seq:SNP
samp:CM_rep1__barc:72___seq:SNP
samp:CM_rep1__barc:74___seq:SNP
samp:CM_rep1__barc:77___seq:SNP
samp:CM_rep1__barc:79___seq:SNP
samp:CM_rep1__barc:81___seq:SNP
samp:CM_rep1__barc:93___seq:SNP
samp:CM_rep1__barc:98___seq:SNP
samp:CM_rep2__barc:27___seq:SNP
samp:CM_rep2__barc:39___seq:SNP
samp:CM_rep2__barc:44___seq:SNP
samp:CM_rep2__barc:49___seq:SNP
samp:CM_rep2__barc:56___seq:SNP
samp:CM_rep2__barc:58___seq:SNP
samp:CM_rep2__barc:60___seq:SNP
samp:CM_rep2__barc:62___seq:SNP
samp:CM_rep2__barc:64___seq:SNP
samp:CM_rep2__barc:65___seq:SNP
samp:CM_rep2__barc:72___seq:SNP
samp:CM_rep2__barc:74___seq:SNP
samp:CM_rep2__barc:77___seq:SNP
samp:CM_rep2__barc:79___seq:SNP
samp:CM_rep2__barc:81___seq:SNP
samp:CM_rep2__barc:93___seq:SNP
samp:CM_rep2__barc:98___seq:SNP
samp:CM_rep3__barc:27___seq:SNP
samp:CM_rep3__barc:39___seq:SNP
samp:CM_rep3__barc:44___seq:SNP
samp:CM_rep3__barc:49___seq:SNP
samp:CM_rep3__barc:56___seq:SNP
samp:CM_rep3__barc:58___seq:SNP
samp:CM_rep3__barc:60___seq:SNP
samp:CM_rep3__barc:62___seq:SNP
samp:CM_rep3__barc:64___seq:SNP
samp:CM_rep3__barc:65___seq:SNP
samp:CM_rep3__barc:72___seq:SNP
samp:CM_rep3__barc:74___seq:SNP
samp:CM_rep3__barc:77___seq:SNP
samp:CM_rep3__barc:79___seq:SNP
samp:CM_rep3__barc:81___seq:SNP
samp:CM_rep3__barc:93___seq:SNP
samp:CM_rep3__barc:98___seq:SNP
samp:CM_rep4__barc:27___seq:SNP
samp:CM_rep4__barc:39___seq:SNP
samp:CM_rep4__barc:44___seq:SNP
samp:CM_rep4__barc:49___seq:SNP
samp:CM_rep4__barc:56___seq:SNP
samp:CM_rep4__barc:58___seq:SNP
samp:CM_rep4__barc:60___seq:SNP
samp:CM_rep4__barc:62___seq:SNP
samp:CM_rep4__barc:64___seq:SNP
samp:CM_rep4__barc:65___seq:SNP
samp:CM_rep4__barc:72___seq:SNP
samp:CM_rep4__barc:74___seq:SNP
samp:CM_rep4__barc:77___seq:SNP
samp:CM_rep4__barc:79___seq:SNP
samp:CM_rep4__barc:81___seq:SNP
samp:CM_rep4__barc:93___seq:SNP
samp:CM_rep4__barc:98___seq:SNP
samp:CM_rep5__barc:27___seq:SNP
samp:CM_rep5__barc:39___seq:SNP
samp:CM_rep5__barc:44___seq:SNP
samp:CM_rep5__barc:49___seq:SNP
samp:CM_rep5__barc:56___seq:SNP
samp:CM_rep5__barc:58___seq:SNP
samp:CM_rep5__barc:60___seq:SNP
samp:CM_rep5__barc:62___seq:SNP
samp:CM_rep5__barc:64___seq:SNP
samp:CM_rep5__barc:65___seq:SNP
samp:CM_rep5__barc:72___seq:SNP
samp:CM_rep5__barc:74___seq:SNP
samp:CM_rep5__barc:77___seq:SNP
samp:CM_rep5__barc:79___seq:SNP
samp:CM_rep5__barc:81___seq:SNP
samp:CM_rep5__barc:93___seq:SNP
samp:CM_rep5__barc:98___seq:SNP
samp:CM_rep1__barc:100___seq:WT
samp:CM_rep1__barc:30___seq:WT
samp:CM_rep1__barc:33___seq:WT
samp:CM_rep1__barc:37___seq:WT
samp:CM_rep1__barc:43___seq:WT
samp:CM_rep1__barc:49___seq:WT
samp:CM_rep1__barc:51___seq:WT
samp:CM_rep1__barc:52___seq:WT
samp:CM_rep1__barc:53___seq:WT
samp:CM_rep1__barc:58___seq:WT
samp:CM_rep1__barc:62___seq:WT
samp:CM_rep1__barc:64___seq:WT
samp:CM_rep1__barc:66___seq:WT
samp:CM_rep1__barc:68___seq:WT
samp:CM_rep1__barc:73___seq:WT
samp:CM_rep1__barc:88___seq:WT
samp:CM_rep1__barc:89___seq:WT
samp:CM_rep1__barc:92___seq:WT
samp:CM_rep1__barc:99___seq:WT
samp:CM_rep2__barc:100___seq:WT
samp:CM_rep2__barc:30___seq:WT
samp:CM_rep2__barc:33___seq:WT
samp:CM_rep2__barc:37___seq:WT
samp:CM_rep2__barc:43___seq:WT
samp:CM_rep2__barc:49___seq:WT
samp:CM_rep2__barc:51___seq:WT
samp:CM_rep2__barc:52___seq:WT
samp:CM_rep2__barc:53___seq:WT
samp:CM_rep2__barc:58___seq:WT
samp:CM_rep2__barc:62___seq:WT
samp:CM_rep2__barc:64___seq:WT
samp:CM_rep2__barc:66___seq:WT
samp:CM_rep2__barc:68___seq:WT
samp:CM_rep2__barc:73___seq:WT
samp:CM_rep2__barc:88___seq:WT
samp:CM_rep2__barc:89___seq:WT
samp:CM_rep2__barc:92___seq:WT
samp:CM_rep2__barc:99___seq:WT
samp:CM_rep3__barc:100___seq:WT
samp:CM_rep3__barc:30___seq:WT
samp:CM_rep3__barc:33___seq:WT
samp:CM_rep3__barc:37___seq:WT
samp:CM_rep3__barc:43___seq:WT
samp:CM_rep3__barc:49___seq:WT
samp:CM_rep3__barc:51___seq:WT
samp:CM_rep3__barc:52___seq:WT
samp:CM_rep3__barc:53___seq:WT
samp:CM_rep3__barc:58___seq:WT
samp:CM_rep3__barc:62___seq:WT
samp:CM_rep3__barc:64___seq:WT
samp:CM_rep3__barc:66___seq:WT
samp:CM_rep3__barc:68___seq:WT
samp:CM_rep3__barc:73___seq:WT
samp:CM_rep3__barc:88___seq:WT
samp:CM_rep3__barc:89___seq:WT
samp:CM_rep3__barc:92___seq:WT
samp:CM_rep3__barc:99___seq:WT
samp:CM_rep4__barc:100___seq:WT
samp:CM_rep4__barc:30___seq:WT
samp:CM_rep4__barc:33___seq:WT
samp:CM_rep4__barc:37___seq:WT
samp:CM_rep4__barc:43___seq:WT
samp:CM_rep4__barc:49___seq:WT
samp:CM_rep4__barc:51___seq:WT
samp:CM_rep4__barc:52___seq:WT
samp:CM_rep4__barc:53___seq:WT
samp:CM_rep4__barc:58___seq:WT
samp:CM_rep4__barc:62___seq:WT
samp:CM_rep4__barc:64___seq:WT
samp:CM_rep4__barc:66___seq:WT
samp:CM_rep4__barc:68___seq:WT
samp:CM_rep4__barc:73___seq:WT
samp:CM_rep4__barc:88___seq:WT
samp:CM_rep4__barc:89___seq:WT
samp:CM_rep4__barc:92___seq:WT
samp:CM_rep4__barc:99___seq:WT
samp:CM_rep5__barc:100___seq:WT
samp:CM_rep5__barc:30___seq:WT
samp:CM_rep5__barc:33___seq:WT
samp:CM_rep5__barc:37___seq:WT
samp:CM_rep5__barc:43___seq:WT
samp:CM_rep5__barc:49___seq:WT
samp:CM_rep5__barc:51___seq:WT
samp:CM_rep5__barc:52___seq:WT
samp:CM_rep5__barc:53___seq:WT
samp:CM_rep5__barc:58___seq:WT
samp:CM_rep5__barc:62___seq:WT
samp:CM_rep5__barc:64___seq:WT
samp:CM_rep5__barc:66___seq:WT
samp:CM_rep5__barc:68___seq:WT
samp:CM_rep5__barc:73___seq:WT
samp:CM_rep5__barc:88___seq:WT
samp:CM_rep5__barc:89___seq:WT
samp:CM_rep5__barc:92___seq:WT
samp:CM_rep5__barc:99___seq:WT
samp:CM_rep1__barc:100___seq:SNP
samp:CM_rep1__barc:31___seq:SNP
samp:CM_rep1__barc:33___seq:SNP
samp:CM_rep1__barc:36___seq:SNP
samp:CM_rep1__barc:37___seq:SNP
samp:CM_rep1__barc:43___seq:SNP
samp:CM_rep1__barc:47___seq:SNP
samp:CM_rep1__barc:53___seq:SNP
samp:CM_rep1__barc:54___seq:SNP
samp:CM_rep1__barc:59___seq:SNP
samp:CM_rep1__barc:63___seq:SNP
samp:CM_rep1__barc:71___seq:SNP
samp:CM_rep1__barc:75___seq:SNP
samp:CM_rep1__barc:78___seq:SNP
samp:CM_rep1__barc:80___seq:SNP
samp:CM_rep1__barc:89___seq:SNP
samp:CM_rep1__barc:95___seq:SNP
samp:CM_rep1__barc:97___seq:SNP
samp:CM_rep2__barc:100___seq:SNP
samp:CM_rep2__barc:31___seq:SNP

                                condition barcode  seq
samp:CM_rep5__barc:3___seq:WT          CM       3   WT
samp:CM_rep3__barc:71___seq:WT         CM      71   WT
samp:CM_rep3__barc:33___seq:SNP        CM      33  SNP
samp:CM_rep3__barc:74___seq:WT         CM      74   WT
samp:CM_rep3__barc:22___seq:WT         CM      22   WT

In [106]:
# merge w/ older annotations: first reset index
rna_col_ann.reset_index(inplace=True)

rna_col_ann["colname"] = rna_col_ann["index"]
rna_col_ann.head()

,index,condition,barcode,seq,colname
0,samp:CM_rep1__barc:1___seq:SNP,CM,1,SNP,samp:CM_rep1__barc:1___seq:SNP
1,samp:CM_rep1__barc:10___seq:SNP,CM,10,SNP,samp:CM_rep1__barc:10___seq:SNP
2,samp:CM_rep1__barc:11___seq:SNP,CM,11,SNP,samp:CM_rep1__barc:11___seq:SNP
3,samp:CM_rep1__barc:12___seq:SNP,CM,12,SNP,samp:CM_rep1__barc:12___seq:SNP
4,samp:CM_rep1__barc:13___seq:SNP,CM,13,SNP,samp:CM_rep1__barc:13___seq:SNP

In [107]:
 #reset index
rna_col_ann.set_index("colname", inplace=True)

In [108]:
rna_col_ann.index.name = None
rna_col_ann.sample(5)

,index,condition,barcode,seq
samp:CM_rep4__barc:45___seq:SNP,samp:CM_rep4__barc:45___seq:SNP,CM,45,SNP
samp:CM_rep1__barc:77___seq:WT,samp:CM_rep1__barc:77___seq:WT,CM,77,WT
samp:CM_rep5__barc:86___seq:WT,samp:CM_rep5__barc:86___seq:WT,CM,86,WT
samp:CM_rep1__barc:42___seq:SNP,samp:CM_rep1__barc:42___seq:SNP,CM,42,SNP
samp:CM_rep3__barc:86___seq:SNP,samp:CM_rep3__barc:86___seq:SNP,CM,86,SNP

## 8. make control ID files

In [109]:
ctrls = all_rna.reset_index()[["comp_id", "samp:CM_rep1__barc:10___seq:WT"]]
ctrls["ctrl_status"] = ctrls.apply(ctrl_status, axis=1)
ctrls.drop("samp:CM_rep1__barc:10___seq:WT", axis=1, inplace=True)
ctrls.ctrl_status.value_counts()

True     126
False     68
Name: ctrl_status, dtype: int64

In [110]:
ctrls.head()

                    comp_id  ctrl_status
0  4670__WILDTYPE_SNP_INDIV        False
1  4707__WILDTYPE_SNP_INDIV        False
2  4695__WILDTYPE_SNP_INDIV        False
3  4651__WILDTYPE_SNP_INDIV        False
4  4655__WILDTYPE_SNP_INDIV        False

## 9. write seq comparison files

In [111]:
dna_col_ann.to_csv("%s/dna_col_ann.seq_comp.mpranalyze.CM.5.Mital.new_back.txt" % mpranalyze_dir, sep="\t")
rna_col_ann.to_csv("%s/rna_col_ann.seq_comp.mpranalyze.CM.5.Mital.new_back.txt" % mpranalyze_dir, sep="\t")

ctrls.to_csv("%s/ctrl_status.seq_comp.mpranalyze.CM.5.Mital.new_back.txt" % mpranalyze_dir, sep="\t", index=False)

all_dna.to_csv("%s/dna_counts.seq_comp.mpranalyze.CM.5.Mital.new_back.txt" % mpranalyze_dir, sep="\t", index=True)
all_rna.to_csv("%s/all_rna_counts.seq_comp.mpranalyze.CM.5.Mital.new_back.txt" % mpranalyze_dir, sep="\t", index=True)